### ISSUE TITLE
Timeout when execute a command

### ISSUE THREAD

**Issue by jricaldi** [appleboy/ssh-action#1]
I have this workflow
```yml
name: Deploy to development environment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Vultr remote machine
      uses: appleboy/ssh-action@master
      with:
        args: >
          --host ${{ secrets.SSH_HOST }} --user ${{ secrets.SSH_USER }} --password ${{ secrets.SSH_PASSWORD }}
          --script 'git checkout master'
          --script 'npm install'
          --script 'npm run build:prod'
```
I got this output:
```
======CMD======
git checkout master
npm install
npm run build:prod
======END======
err: Already on 'master'
out: Your branch is up-to-date with 'origin/master'.
2019/09/08 08:54:06 Error: command timeout
err: Run Command Timeout!
##[error]Docker run failed with exit code 1
```

How can I increase the timeout?
