### ISSUE TITLE
Warning: Permanently added the RSA host key for IP address '13.***9.***.59' to the list of known hosts.

### ISSUE THREAD

**Issue by widada** [appleboy/ssh-action#100]
Hi, I tried to deploy my app using this ssh-action.

but I got this warning

```
err: Warning: Permanently added the RSA host key for IP address '13.***9.188.**' to the list of known hosts.
err: From github.com:widada/cicd-demo
err:  * branch            master     -> FETCH_HEAD
err:    3c7c799..6e1cf20  master     -> origin/master
out: Updating 3c7c799..6e1cf20
out: Fast-forward
out:  .github/workflows/node.js.yml | 20 +++++++++++++++++++-
out:  routes/calculate.js           |  2 +-
out:  2 files changed, 20 insertions(+), 2 deletions(-)
2020/12/28 13:28:15 Process exited with status 127
err: bash: line 2: npm: command not found
err: bash: line 3: pm2: command not found
```

and this is my .yml file

```
 deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/app/cicd-demo
          git pull origin master
          npm install --production
          pm2 restart 0
```
