### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by adamf0** [appleboy/ssh-action#101]
I have a complaint why after I can access the server via ssh but I can't run the command "git pull"? I've changed the permissions with the command "sudo chown -R <username> .git /" or "chmod -R 755 .git" but it still doesn't work, if it works then the yml and php files will get permission denied and still don't change anything. because i ran out of options i tried to delete the folder and the clone still can't come back, permission is always denied. please help and direction.

problem.
![problem git pull](https://user-images.githubusercontent.com/59599463/106710412-7a35c000-6628-11eb-8d02-cbede52eac21.PNG)
command.
![cd git pull](https://user-images.githubusercontent.com/59599463/106710426-802ba100-6628-11eb-84f9-f25c636e5f26.PNG)
alternative command.
![image](https://user-images.githubusercontent.com/59599463/106710736-0ea02280-6629-11eb-8df5-0d8ddd044fc7.png)
next problem
![problem git pull 2](https://user-images.githubusercontent.com/59599463/106710839-2bd4f100-6629-11eb-9043-6a5484096f19.PNG)

**Comment by marekgoj** [comment]
The problem here is that you run commands:
```
sudo su
git pull origin master
```
and the second command is still running as original user

Instead you should run
```
sudo su -c 'git pull origin master'
```

**Comment by appleboy** [comment]
Thanks for @marekgoj suggestion. Please try it out.

**Comment by ddjerqq** [comment]
I am running a very simple script with [act](https://github.com/nektos/act) and it is giving me an error when I try to execute the commands it gives me `/var/run/act/actions/appleboy-ssh-action@master/entrypoint.sh: Permission denied`
the script is very simple for testing purposes, its just `echo success`, so it definitely is not the same issue as described above.

I have my own server setup, logging in from a regular terminal works just fine without issues, however, even with the same credentials, it fails from github actions workflow, when invoked with `act`.


```yaml
name: Build and deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Restart docker-compose 🔁
        uses: appleboy/ssh-action@master
        with:
#         local server, which works from a regular terminal
          host: 192.168.0.111
          username: "CORRECT_USERNAME"
          password: "CORRECT_PASSWORD"
          script: echo success
```
could this be an issue with `act`?
