### ISSUE TITLE
ssh: handshake failed: ssh: overflow reading version string

### ISSUE THREAD

**Issue by KiranI-Bsw** [appleboy/ssh-action#104]
I'm using password authentication and getting. "ssh: handshake failed: ssh: overflow reading version string" everytime. Not able to resolve, please help. By the way it is working from my pc.

here's my yml
```
- name: Run SSH commands for deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WEB_HOST }}
        port: ${{ secrets.WEB_PORT }}
        username: ${{ secrets.WEB_USERNAME }}
        password: ${{ secrets.WEB_PASSWORD }}
        script: |
          whoami
          ls -l
```

logs:
Run appleboy/ssh-action@master
/usr/bin/docker run --name e47784e41ee16b45258586ccb4a7d42cfe_a92a21 --label 5588e4 --workdir /github/workspace --rm -e JAVA_HOME_8.0.282_x64 -e JAVA_HOME -e JAVA_HOME_8_0_282_X64 -e INPUT_HOST -e INPUT_PORT -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_SCRIPT -e INPUT_PASSPHRASE -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Blacklight-Web/Blacklight-Web":"/github/workspace" 5588e4:7784e41ee16b45258586ccb4a7d42cfe
======CMD======
whoami
ls -l

======END======
2021/02/16 05:54:08 ssh: handshake failed: ssh: overflow reading version string
