### ISSUE TITLE
Artisan Commands Fail

### ISSUE THREAD

**Issue by SturmB** [appleboy/ssh-action#106]
I am attempting to use this to deploy a Laravel app to the production server. In the process, Composer and Node must install the dependencies, a symlink must be created, and a few `php artisan …` commands must be run. This is where it falls apart.

Please have a look at the result of the action here; in particular, the "SSH Prep for Production" step:
https://github.com/skyunlimitedinc/ays/runs/1961771177?check_suite_focus=true

In it, there are several error results that seem to correlate to when the Artisan commands are being executed:
```
out: In StreamHandler.php line 172:
out:                                                                                
out:   There is no existing directory at "/home/runner/work/ays/ays/storage/logs"   
out:   and it could not be created: Permission denied                               
out:                                                                                
```
This looks like it's trying to run the Artisan commands on the runner, **not** the production server as I expected. If that were the case, then it would be running in "/var/www/html/…", not "/home/runner/work/ays/ays/…". I would also expect to see some sort of "success" message from each command, such as "Route cache cleared!"

There also appear to be errors during the `npm install` command, but I am not 100% sure if that's normal. My gut tells me that it also suffers from the same problem; expecting to be run in `/var/www/html` on the production server and not `/home/runner/work/ays/ays` on the Github Action VM.

Here is the relevant section of my workflow file:
```yaml
      - name: SSH Prep for Production
        uses: appleboy/ssh-action@v0.1.4
        env:
          IP: ${{ secrets.IP }}
          USER_NAME: ${{ secrets.USER_NAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.TRAVIS_SSH_KEY }}
          envs: IP,USER_NAME,DEPLOY_PATH
          script_stop: true
          script: |
            # Install dependencies
            cd "$DEPLOY_PATH" && composer install --no-progress --no-interaction --optimize-autoloader --no-dev
            cd "$DEPLOY_PATH" && npm install

            # Prep for production
            cd "$DEPLOY_PATH" && npm run production
            cd "$DEPLOY_PATH" && php artisan cache:clear
            cd "$DEPLOY_PATH" && php artisan key:generate
            cd "$DEPLOY_PATH" && ln -s "$DEPLOY_PATH/storage/app/public" "$DEPLOY_PATH/public/storage"
            cd "$DEPLOY_PATH" && php artisan config:cache
            cd "$DEPLOY_PATH" && php artisan route:cache
```

Please tell me if I am doing something wrong.
