### ISSUE TITLE
Suddenly getting "Error: can't connect without a private SSH key or password"

### ISSUE THREAD

**Issue by eli-s-r** [appleboy/ssh-action#108]
Hi, I've been using this fantastic tool for several months now and haven't encountered any issues until this point. However, despite there not being any changes to my script or to my configuration, I'm suddenly receiving `Error: can't connect without a private SSH key or password`. I am indeed using a private key -- below is my configuration for the action: 

```
- name: SSH into droplet
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.DROPLET_HOST }}
    username: ${{ secrets.DROPLET_USERNAME }}
    passphrase: ${{ secrets.DROPLET_PASSWORD }}
    key: ${{ secrets.DROPLET_PRIVATE_KEY }}
    envs: COMMIT_SHA
    script_stop: true
    script: |
      git fetch origin
      git merge $COMMIT_SHA
```

What could have changed that may be causing this issue?
