### ISSUE TITLE
how to add time

### ISSUE THREAD

**Issue by hello1983** [appleboy/ssh-action#109]
schedule:
    - cron: '10 16 * * *'

You have an error in your yaml syntax on line 4

**Comment by appleboy** [comment]
```yaml
name: "example-cron-action"
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute
```

see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
