### ISSUE TITLE
Why is there `err:` in the output even if everything is fine?

### ISSUE THREAD

**Issue by floatingpurr** [appleboy/ssh-action#110]
I have a very simple step built on ssh-action

```yml
    steps:
      - name: execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Go to the project space"
            cd $HOME/actions_workspace/actions-sample
            echo "Pulling the repo from the remote server"
            git pull origin main
            echo "Building the new container"
            docker-compose build
```

It works fine, but this is the output:

```bash
======CMD======
echo "Go to the project space"
cd $HOME/actions_workspace/actions-sample
echo "Pulling the repo from the remote server"
git pull origin main
echo "Building the new container"
docker-compose build

======END======
out: Go to the project space
out: Pulling the repo from the remote server
err: From github.com:floatingpurr/my-test-repo
err:  * branch            main       -> FETCH_HEAD
err:    3961b2c..26e6abe  main       -> origin/main
out: Updating 3961b2c..26e6abe
out: Fast-forward
out:  README.md          |  2 +-
out:  docker-compose.yml | 12 ++++++------
out:  2 files changed, 7 insertions(+), 7 deletions(-)
out: Building the new container
err: my-test-actions uses an image, skipping
==============================================
✅ Successfully executed commands to all host.
==============================================
```

I'm just wondering the reason why I see `err:` in the action output and not just `out` (as I would have expected)
