### ISSUE TITLE
Unable to find image 'xxx' locally

### ISSUE THREAD

**Issue by garypang13** [appleboy/ssh-action#114]
```
    - name: remote ssh command
      uses: appleboy/ssh-action@master
      continue-on-error: true
      if: env.SSH_PRIVATE_KEY
      with:
        host: op.supes.top
        username: root
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cp -R /www/wwwroot/op.supes.top/packages/keep/common/* /www/wwwroot/op.supes.top/packages/${{ env.MTARGET }}/
          cp -R /www/wwwroot/op.supes.top/packages/keep/${{ env.MTARGET }}/* /www/wwwroot/op.supes.top/packages/${{ env.MTARGET }}
```

```
Unable to find image '5588e4:5eeb6cb556054d1eb78d3554f686ecd4' locally
docker: Error response from daemon: pull access denied for 5588e4, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```
