### ISSUE TITLE
Colliding environment variables

### ISSUE THREAD

**Issue by Tracer1337** [appleboy/ssh-action#115]
# Issue

Apparently, naming an environment variable ``HOST``, ``PORT`` or ``DOCKER_HOST`` breaks the script.

1. The  ``HOST`` and ``PORT`` variables cause the ``connection refused`` error, which has to have occurred internally in the ssh-action. (The full step is shown in the appendix)
```
======CMD======
docker run \
  # ...
  --env HOST \
  --env PUBLIC_PORT \
  --env PROTOCOL \

======END======
2021/04/21 16:05:26 dial tcp some-host:8300: connect: connection refused
```

2. The ``DOCKER_HOST`` variable which, if you look closely into the way to long command above, is used internally and also causes an error.

```
/usr/bin/docker run --name ... -e DOCKER_HOST -e DOCKER_PUBLIC_PORT -e DOCKER_PROTOCOL -e DOCKER_PORT ...
docker: Cannot connect to the Docker daemon at tcp://some-host:2375. Is the docker daemon running?.
See 'docker run --help'.
```

# Proposal

Add an "env blacklist" or "internal env variables" section to the README which contains all env variables which may cause side effects.

# Appendix

Full steps from ``.github/workflow/my-workflow.yml``

1.
```yaml
- name: Some Step
  uses: appleboy/ssh-action@v0.1.4
  env:
    HOST: some-host
    PORT: 8300
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    envs: HOST,PORT
    script: |
      docker run \
        --env HOST \
        --env PORT
```

2.
```yaml
- name: Some Step
  uses: appleboy/ssh-action@v0.1.4
  env:
    DOCKER_HOST: some-host
    DOCKER_PUBLIC_PORT: "4000"
    DOCKER_PROTOCOL: http
    DOCKER_PORT: "8300"
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    envs: DOCKER_HOST,DOCKER_PUBLIC_PORT,DOCKER_PROTOCOL,DOCKER_PORT
    script: |
      docker run \
        --publish $DOCKER_PORT:8080 \
        --env HOST=$DOCKER_HOST \
        --env PUBLIC_PORT=$DOCKER_PUBLIC_PORT \
        --env PROTOCOL=$DOCKER_PROTOCOL \
        some-image
```
