### ISSUE TITLE
Running docker-compose up results in TimeOut Error

### ISSUE THREAD

**Issue by NikoMontana** [appleboy/ssh-action#117]
When running docker-compose up with this action the ssh connection still is waiting for, well i don´t know what it is waiting for to be honest. My Container get build and is running but the result from the Action is "failed" as it timeouts.

```
  deploy_to_digital_ocean_dropplet:
    name: Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -r repository
            gh repo clone github/repository
            cd repository
            docker stop $(docker ps -a -q)
            docker-compose up --build --force-recreate
```
