### ISSUE TITLE
Error: can't connect without a private SSH key or password

### ISSUE THREAD

**Issue by wilburt** [appleboy/ssh-action#119]
Unlike #108, mine is triggered even when the workflow is started by a push.

The step causing the issue is this:
```
- name: Copy file via scp
  uses: appleboy/scp-action@master
  env:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.KEY }}
    port: ${{ secrets.PORT }}
  with:
    source: "./"
    target: "/opt/site" 
```

And the value of the key in Github secrets is in this format:

> -----BEGIN OPENSSH PRIVATE KEY-----
> [REDACTED]
> -----END OPENSSH PRIVATE KEY-----

The log outputted for the problematic step contains:
```
env:
    host: ***
    username: ***
    key: ***
  
    port: ***
```
I can't seem to figure out what I am doing wrong.

**Comment by wilburt** [comment]
I changed the keys to all caps and it worked.

**Comment by gusttavodev** [comment]
On https://github.com/settings/installations

Disable key lock and security related apps to upload your keys

![image](https://user-images.githubusercontent.com/39275291/129481485-c9fd5aa1-4b47-448c-a8a4-dda06fd45505.png)

**Comment by RossComputerGuy** [comment]
I have the same problem but I haven't found a fix:
```

Run appleboy/ssh-action@master
  with:
    port: 22
    sync: false
    use_insecure_cipher: false
    timeout: 30s
    command_timeout: 10m
    proxy_port: 22
    proxy_timeout: 30s
    proxy_use_insecure_cipher: false
    script_stop: false
    debug: false
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: MidstallSoftware/website
    host: 
    username: 
    key: 
    script: sudo systemctl restart docker-midstall
```
https://github.com/MidstallSoftware/website/actions/runs/1514411593/workflow

**Comment by flyon** [comment]
> I changed the keys to all caps and it worked.

sorry, which keys @wilburt ? the keys of the YAML file like host, key, username etc?

**Comment by bhaveshtank** [comment]
facing the same issue.
@wilburt what changes did you make ?

**Comment by indymaat** [comment]
@wilburt what keys did you change? Did you capitalize this:
```
env:
    host: ***
    username: ***
    key: ***
    port: ***
```
to this:
```
env:
    HOST: ***
    USERNAME: ***
    KEY: ***
    PORT: ***
```
