### ISSUE TITLE
Another "Permission denied (publickey)" for Digital Ocean

### ISSUE THREAD

**Issue by chozzz** [appleboy/ssh-action#123]
I realized this may have been reported and solved couple of times, I have read all the relevant threads though none of them seem to help with me. I am pretty sure I am not missing anything. So here's what I have done.

1. I created a new key-pair with the following command
`ssh-keygen -t rsa -b 4096 -m PEM -C "myproject@github-actions"`

2. Let's say the name of the key file is `my_key`. Then, I added `my_key.pub` to **DigitalOcean Settings -> Security -> SSH Keys**
3. I added the public key into the droplet's `~/.ssh/authorized_keys`.
4. Created the secrets in github repo
- `SSHKEY` is the private key of `my_key`
- `USERNAME` is `root`
- `HOST` is the IP address of the droplet
- `PORT` is `22`

![image](https://user-images.githubusercontent.com/5223310/120899604-29c88080-c663-11eb-8725-511b663dd138.png)
5. Created the `master.yml` at the repo.
**master.yml**

```
name: Build and deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Execute commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /var/www/html
            git pull origin master
            npm install --only=prod
            cp .env.example .env
            npm run build
            pm2 restart myproject.com
```

And the Github action keeps giving me this output
```
/usr/bin/docker run --name a33c1711f20155880481f9e04aa2eec32bf61_b91be8 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_USERNAME -e INPUT_KEY -e INPUT_PORT -e INPUT_SCRIPT_STOP -e INPUT_SCRIPT -e INPUT_PASSPHRASE -e INPUT_PASSWORD -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/myproject/myproject":"/github/workspace" 8a33c1:711f20155880481f9e04aa2eec32bf61
======CMD======
cd /var/www/myproject
git pull origin master
npm install --only=prod
cp .env.example .env
npm run build
pm2 restart myproject.com

======END======
2021/06/05 16:44:24 Process exited with status 1
err: Permission denied (publickey).
err: fatal: Could not read from remote repository.
err: 
err: Please make sure you have the correct access rights
err: and the repository exists.
```

However, if I try to access via SSH from my local machine, I can connect to it just fine.

**~/..ssh/config**
```
Host mydroplet
  User root
  HostName <REDACTED>
  IdentityFile ~/.ssh/my_key
  IdentitiesOnly yes
  Port 22
```
And then simply run `ssh mydroplet` - and I get connected!

Any idea what I might be missing here?
Let me know if you need further informations
