### ISSUE TITLE
can't use envs in a specified .sh file

### ISSUE THREAD

**Issue by Blankll** [appleboy/ssh-action#124]
I use this action to pass envs as bellow:
```yaml
- name: Run Script
      uses: appleboy/ssh-action@master
      env: 
        ENV: 'develop'
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SECRET }}
        script_stop: true
        envs: ENV,MYSQL_USER,PASSWORD
        script: script.sh
```
in the script.sh the envs was not defined
is there any way to use the envs in a script file

**Comment by Jasperhino** [comment]
I ran into the same problem, maybe this is a Problem with when github actions actually loads the env variables?

**Comment by appleboy** [comment]
See the documentation: https://github.com/appleboy/ssh-action#pass-environment-variable-to-shell-script

**Comment by Blankll** [comment]
yes, I also found export or pass the env variable in script can work fine like below:
```shell
- name: Run Script
      uses: appleboy/ssh-action@master
      env: 
        ENV: 'develop'
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SECRET }}
        script_stop: true
        envs: ENV,MYSQL_USER,PASSWORD
        script: |
         ENV=develop MYSQL_USER:=${{ secrets.MYSQL_USER }} PASSWORD:=${{ secrets.PASSWORD }} script.sh
```
but I just think if we can use env directly in the script that may more helpful?

**Comment by ioogle** [comment]
This can also work:

```yaml
     - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          envs: SMTP_HOST,SMTP_USERNAME,SMTP_PASSWORD
          script: ${{ secrets.REMOTE_COMMAND }}
```

where the `REMOTE_COMMAND` is:

```sh
#!/bin/sh

cd ~/goquant-devops
docker-compose -f docker-compose.core.yml -f docker-compose.core.test.yml stop user-api user-rpc
docker-compose -f docker-compose.core.yml -f docker-compose.core.test.yml rm -f user-api user-rpc
docker-compose -f docker-compose.core.yml -f docker-compose.core.test.yml pull
docker image prune -f

kill -9 $(sudo lsof -t -i:55031)
kill -9 $(sudo lsof -t -i:55032)

SMTP_HOST=$SMTP_HOST SMTP_USERNAME=$SMTP_USERNAME SMTP_PASSWORD=$SMTP_PASSWORD \
  docker-compose -f docker-compose.core.yml -f docker-compose.core.test.yml config > ~/config.txt

SMTP_HOST=$SMTP_HOST SMTP_USERNAME=$SMTP_USERNAME SMTP_PASSWORD=$SMTP_PASSWORD \
  docker-compose -f docker-compose.core.yml -f docker-compose.core.test.yml up -d user-api user-rpc
```
