### ISSUE TITLE
Git Clone Permissions Denied (public key) error - Only via Actions

### ISSUE THREAD

**Issue by Forsak3nBacon** [appleboy/ssh-action#127]
I've been trying to set up a deploy action to clone my repo to a Digital Ocean droplet. 
I've set all the keys up correctly in both the droplet and my github account (public key). 
I can clone fine within my SSH terminal to the droplet. 
Using `ssh -T git@github.com` matches the same username as my repo path used in clone.
`ssh-add -l` shows the same footprint as my public key setting in my github profile.

Here's my deploy.yml - I've replace/removed my repo path for this post:
```
name: Build & Deploy
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Tavern Bot
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          
          script: |
            cd up-tavern-bot
            mv db .. #Ensure we don't wipe the DB
            ls -a | xargs rm -rf -f #Delete all files, including hidden
            git clone git@github.com:USERNAME/Path.git . #clone the repo into current folder
            cd .. #Move up so we can move DB back in.
            mv db up-tavern-bot/ #Move DB back in.
            echo 'Deployment successful to digital ocean'
```
Here's the result from the action - ignore the cant move db:
```
======END======
err: mv: cannot stat 'db': No such file or directory
err: rm: refusing to remove '.' or '..' directory: skipping '.'
err: rm: refusing to remove '.' or '..' directory: skipping '..'
err: Cloning into '.'...
err: git@github.com: Permission denied (publickey).
err: fatal: Could not read from remote repository.
err: 
err: Please make sure you have the correct access rights
err: and the repository exists.
err: mv: cannot stat 'db': No such file or directory
out: Deployment successful to digital ocean
==============================================
✅ Successfully executed commands to all host.
==============================================
```
To prove I can git clone from within an SSH terminal - here's my results from using the same git clone command as my action:
[https://gyazo.com/c19cd56b60198b4249125ffb3b8d672f](https://gyazo.com/c19cd56b60198b4249125ffb3b8d672f)
