### ISSUE TITLE
Git pull not working in remote using env variable

### ISSUE THREAD

**Issue by varunyn** [appleboy/ssh-action#128]
Following is my workflow config, it seems there is some issue when passing env. Git pull worked in past, no value is changed but it seems currently not working when passing password in secrets. Any help is appreciated
```
 steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        env:
          PASS: ${{ secrets.PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          timeout: 1200s
          command_timeout: 20m
          script: |
            git pull https://varunyn:$PASS@github.com/...
```

Error
```
remote: Invalid username or password.
err: fatal: Authentication failed for '***github.com/varunyn/...
```

**Comment by secure12** [comment]
You could use a deploy key to work around this.
Go to your repository -> Settings -> Deploy keys -> Add deploy key, then paste your ssh public key (usually in ~/.ssh and ends with _pub) in the "key" section.
You can verify that it works using:
`sudo -u $(whoami) ssh -T git@github.com`
It would say you are successfully authenticated.
To pull the repository use
`git pull git@github.com:{org_name}/{repo_name}.git`

**Comment by varunyn** [comment]
Thanks, in this case, I need to have my private key already on the server. Is there any other workaround without storing any credentials on the server?

**Comment by secure12** [comment]
Specify the environment variable names under with: envs:

**Comment by secure12** [comment]
```
 steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        env:
          PASS: ${{ secrets.PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: PASS
          timeout: 1200s
          command_timeout: 20m
          script: |
            git pull https://varunyn:$PASS@github.com/...

```
