### ISSUE TITLE
Don't work Multiple Commands

### ISSUE THREAD

**Issue by JoeWatanabe** [appleboy/ssh-action#129]
# issue
I created multiple command while referencing the section #Multiple Commands of this repository's README.md.
But only the first of multiple commands will be executed.

# workflow yaml
```
name: Test

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: connect by ssh
        uses: appleboy/ssh-action@v0.1.4
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ls -al
```

# workflow result 
```
======CMD======
whoami
ls -al

======END======
out: ***
==============================================
✅ Successfully executed commands to all host.
==============================================
``` 

Looking at this result, we can see that only "whoami" is being executed.
The OS of the server to connect to is Windows, is it related?
