### ISSUE TITLE
How to pass multiple environment variables

### ISSUE THREAD

**Issue by EYHN** [appleboy/ssh-action#14]
I can't find it in the README.
I tried passing an array , but got an error

**Comment by appleboy** [comment]
```yaml
  - name: pass environment
    uses: appleboy/ssh-action@master
+   env:
+     FOO: "BAR"
+     BAR: "FOO"
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
+     envs: FOO,BAR
      script: |
        echo "I am $FOO"
        echo "I am $BAR"
```

Try it.
