### ISSUE TITLE
Access programs of vm

### ISSUE THREAD

**Issue by Tobjoern** [appleboy/ssh-action#140]
Hey,
I'm new to github actions, so this question may seem trivial.
On a VM I run a docker swarm, which uses various (private) images, which are hosted on the google container registry.
In order to pull those images, I'm authenticated via the 'gcloud' utility (which is also installed on the system).
When I manually connect via 'ssh root@xx.xxx.xxx.xx' I can simply access the gcloud utility (or any other program installed on the vm for that matter).
However, when I enter via 'ssh-action' I get the error: 'gcloud: command not found'.
What is the solution to this issue? Or is this the expected behaviour, and I need to create a custom script.

Current code:
```
 - name: Update Swarm
      uses: appleboy/ssh-action
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            gcloud auth list
```
