### ISSUE TITLE
Login with password and private key

### ISSUE THREAD

**Issue by hamuto** [appleboy/ssh-action#142]
I have a job : 
```
    # PREDEPLOY 
    steps:
      - name: Test SSH for Back Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_PROD_BACK_SERVER}}
          username: ${{ secrets.SSH_BACK_USER }}
          key: ${{secrets.SSH_KEY_BACK}}
          password: root
          script: pwd
```

The error I get is: 
> 2021/11/05 10:10:42 can't set password and key at the same time

If I don't put the password parameter, I get a timeout.
The answer at : https://github.com/appleboy/ssh-action/issues/121 didn't solve my issue
