### ISSUE TITLE
error while ssh into ipv6 server.

### ISSUE THREAD

**Issue by jainamoswal** [appleboy/ssh-action#146]
My server only connects over ipv6, and while using this action gives me error »

`2022/01/09 14:49:09 dial tcp: address tcp/4f8: unknown port`

**Request you to add support for ipv6 servers also.** 👀

_(This is duplicate issue of #97, I don't know why the author closed it. 🤷‍♂️)_

**Comment by themustafaomar** [comment]
++++1

**Comment by SuntuapDigital** [comment]
same

**Comment by dglalperen** [comment]
same here

**Comment by appleboy** [comment]
I will take it.

**Comment by cyril23** [comment]
> I will take it.

thanks a lot. I will test it once completed. Your Github action seems to be the only one supporting multiple commands, multiple servers etc., which makes usage very convenient.

I've tried a few other Github actions like https://github.com/marketplace/actions/remote-ssh-commands and its origin https://github.com/marketplace/actions/run-ssh-command but they didn't work either on IPv6. Maybe https://github.com/marketplace/actions/ssh-deploy works (according to https://github.com/easingthemes/ssh-deploy/issues/125) 

but for now I just need to rent another IPv4...

**Comment by mushroom1324** [comment]
Waiting for it since public IPv4 on AWS now charges over $40  every year..

**Comment by timreibe** [comment]
bump, we need this too!

**Comment by appleboy** [comment]
reference the issue on GitHub Action Runner: https://github.com/actions/runner-images/issues/668

**Comment by appleboy** [comment]
Hi All, 

Please help to try the following instructions:

```yaml
  testing06:
    name: testing ipv6
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: testing ipv6 for command
        run: |
          curl -m 9 --ipv6 --verbose https://google.com

      - name: testing ipv6
        uses: appleboy/ssh-action@master
        with:
          host: 2402:1f00:8000:800::2628
          username: ubuntu
          password: ${{ secrets.OVH_PASSWORD }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            whoami
```

Please make sure you add the new attribute `protocol: tcp6`.
