### ISSUE TITLE
GitHub Actions `::set-output`

### ISSUE THREAD

**Issue by afonsojramos** [appleboy/ssh-action#147]
After a few tries I have given up on trying to make this work by myself. I think that it might be related to this action. I was trying to use GitHub Actions's `::set-output`, however, it seems that it doesn't work with this actions scripts, am I correct?

Below I have a workflow that uses this action, and have tried to save the output of the `Get Previous Successfuly Run Tag` step to use it later. In a run of this [workflow](https://github.com/aquelemiguel/parrot/runs/4755422869?check_suite_focus=true) it seemed that id didn't work. Do you have any idea why?

```yml
deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Get Previous Successfuly Run Tag
      uses: appleboy/ssh-action@master
      id: version
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: echo "::set-output name=LAST_RUNNING_TAG::$(docker ps | grep 'v[[:digit:]]*.[[:digit:]]*.[[:digit:]]*' -ow)"
[...]
    - name: Check Status of New Image With Fallback Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: if [ ! "$(docker ps | grep ghcr.io/${{ github.repository }}:${{ github.ref_name }})" ]; then docker run -d --env-file .env ghcr.io/${{ github.repository }}:${{ steps.version.outputs.LAST_RUNNING_TAG }};  fi
```
