### ISSUE TITLE
Feature request: Nicer way to pass all ENV variables to script

### ISSUE THREAD

**Issue by AnderUstarroz** [appleboy/ssh-action#148]
Having to define one by one all github secrets on `env` and then pass them one by one to `envs` is cumbersome. Ideally adding a flag for passing all github secrets down to the script.

**Comment by appleboy** [comment]
@AnderUstarroz OK. Got it.

**Comment by AnderUstarroz** [comment]
Thanks @appleboy other than this is the best SSH package for Github actions I have found. But with easier/cleaner ENV management would be perfect. 

For instance I have a project using about 20 Env variables and Docker picks the right ones just by the `--env-list`:

```
obs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          export_all_envs: true    
          script: |
            docker run --env-list ./env.list MY_IMAGE:latest

```
Where **export_all_envs**  Exports al github envs and secrets down to the script so they can be used normally like:
```
echo $MY_ENV
```

**Comment by AnderUstarroz** [comment]
The quickest way to test if the feature works would be just by printing the env vars with **printenv**. It should display all github secrets: ${{ secrets.* }}

**all_env**: Injects all Github secrets as environment variables within the script.

**Comment by peterschwarzdev** [comment]
I would say this is the major issue of the package at the moment, and the only reason we didn't use it in production (Too much manual work when having certain number of variables). But if this feature is applied would be awesome!

**Comment by appleboy** [comment]
Maybe I can export all `ENVS` with `GITHUB_` and `INPUT_` as prefixes as below:

![Screen Shot 2022-02-06 at 3 24 02 PM](https://user-images.githubusercontent.com/21979/152671388-9b5c4c6f-1b70-4ad2-9aee-bd090d922325.png)

so developer can use all variables in the script.

**Comment by appleboy** [comment]
@AnderUstarroz I can't add repository secret as global env dynamically so the best way is to define secret as environment manually.

**Comment by AnderUstarroz** [comment]
@appleboy I see.. but still would be super useful if we can have all env automatically exported. Regarding Github secrets we can define them just once within the global space of a Github action :

```
env:
  SOME_VARIABLE: some_value  
  ANOTHER_VARIABLE: some_other_value  <-- Here all the variables within the Task global space

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          all_envs: true    
          script: |
           printenv <----- Should display SOME_VARIABLE, ANOTHER_VARIABLE and ideally also GITHUB_* and INPUT_*

```

**Comment by peterschwarzdev** [comment]
@appleboy agree with @AnderUstarroz  on this one, if we have to define the github secrets manually only once at the root of the file that will not really be a problem. But at the moment we have to define over and over which variables are passed down to the script on every job which is a lot of boilerplate and hard to maintain.

**Comment by appleboy** [comment]
@peterschwarzdev @AnderUstarroz OK. I understand your requirement. I will add a new parameter `all_envs` to pass all environments to the host.

**Comment by simonv3** [comment]
This would be great!

**Comment by alpavlove** [comment]
Looking forward to having this!

**Comment by Sirvaude** [comment]
Is it currently possible?

**Comment by nekiro** [comment]
Was this implemented?

**Comment by appleboy** [comment]
@peterschwarzdev @nekiro 

```yaml
    - name: pass all ENV variables to the script
      uses: appleboy/ssh-action@master
      env:
        INPUT_FOO: "BAR"
        INPUT_AAA: "BBB"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        allenvs: true
        script: |
          echo "I am $INPUT_FOO, thanks"
          echo "I am $INPUT_AAA, thanks"
          echo "$GITHUB_BASE_REF"
          echo "$GITHUB_REF"
```

Add `allenvs` flag to pass the all enviroments to the scripts, only support the prefix value as `INPUT_` and `GITHUB_`

**Comment by abhinayagarwal** [comment]
> Add `allenvs` flag to pass all environments to the scripts, only support the prefix value as `INPUT_` and `GITHUB_`

@appleboy Is there a reason why you only allow to pass environments starting with `INPUT_` and `GITHUB_` ?

**Comment by appleboy** [comment]
@abhinayagarwal 

Because the GitHub Action Container by default will pass in variables that start with `INPUT_` and `GITHUB_`.

**Comment by abhinayagarwal** [comment]
Let's say I have the following step where I already have N number of env variables, none of which start with either `INPUT_` or `GITHUB_`:

```
 - name: pass all ENV variables to the script
      uses: appleboy/ssh-action@v1.0.0
      env:
        FOO_1: "BAR_1"
        FOO_2: "BAR_2"
        ...
        FOO_N: "BAR_N"
      with:
        envs: FOO_1, FOO_2, ..., FOO_N 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
```

As you can see I have to pass all of these env manually using `envs`. Adding `allenvs: true` support for these environment variables and automatically supplying them to the script would be nice, without having to append them with `INPUT_` or `GITHUB_`.
