### ISSUE TITLE
Can not access with ssh key gen. handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

### ISSUE THREAD

**Issue by ThanhDeveloper** [appleboy/ssh-action#153]
I followed the steps you instructed to generate an rsa ssh key to manipulate the github action in my application.
Steps and input output that I got:
```
nguyenthanh@MacBook-Pro-cua-Nguyen NextZone % ssh-keygen -t ed25519 -a 200 -C "my_email@gmail.com"  
Generating public/private ed25519 key pair.
Enter file in which to save the key (/Users/nguyenthanh/.ssh/id_ed25519): 
/Users/nguyenthanh/.ssh/id_ed25519 already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /Users/nguyenthanh/.ssh/id_ed25519
Your public key has been saved in /Users/nguyenthanh/.ssh/id_ed25519.pub
The key fingerprint is:
SHA256:uSutQV7ZxydR2SCGgifHKQBJd2sIlV9EgUdJ8l0IQOH1rU13s my_email@gmail.com
The key's randomart image is:
+--[ED25519 256]--+
|oo++oo+&O==oo o+ |
|...   O.%*.o o. .|
|     . B .E .    |
|         + . .   |
|      . S . + .  |
|     o . . . o   |
|      o..        |
|      ....       |
|      .o.        |
+----[SHA256]-----+
nguyenthanh@MacBook-Pro-cua-Nguyen NextZone % cat ~/.ssh/id_ed25519.pub | ssh root@68.183.xxx.xxx 'cat >> .ssh/authorized_keys'
Enter passphrase for key '/Users/nguyenthanh/.ssh/id_rsa': 
nguyenthanh@MacBook-Pro-cua-Nguyen NextZone % cat ~/.ssh/id_ed25519.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWrbMxQ+XJEqCHnf8XcdJdsadNjNfpasFho/9paBvJ my_email@gmail.com
nguyenthanh@MacBook-Pro-cua-Nguyen NextZone % 
```
My workflow file
```
pull_and_publish_to_cloude_server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            whoami
            ls -al
```

I added some variables in my github action config as follows:
- HOST: 68.183.xxx.xxx
- USERNAME: root
- KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWrbMxQ+XJEqCHnf8XcdJdsadNjNfpasFho/9paBvJ my_email@gmail.com
- PORT: 22
- PASSPHRASE: my passpharase

Output github action 

![image](https://user-images.githubusercontent.com/48196420/157053850-7d3b5d40-9571-459d-a646-95e0f1a96e83.png)

Login success at local machine macos
```
nguyenthanh@MacBook-Pro-cua-Nguyen NextZone % ssh root@68.183.x.xxx 
Enter passphrase for key '/Users/nguyenthanh/.ssh/id_rsa': 
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Mar  7 14:15:14 UTC 2022

  System load:              0.0
  Usage of /:               6.3% of 48.29GB
  Memory usage:             20%
  Swap usage:               0%
  Processes:                118
  Users logged in:          0
  IPv4 address for docker0: 172.17.0.1
  IPv4 address for eth0:    10.1x.0.x
  IPv4 address for eth0:    110.1x.0.x
  IPv6 address for eth0:    2400:6180:0:d0::1457:1001
  IPv4 address for eth1:    10.1x.0.x

16 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


*** System restart required ***
Last login: Mon Mar  7 14:02:52 2022 from 14.165.108.112

```
I tried on my mac to login via ssh ubuntu server via ssh root@68.183.xxx.xxx and everything is perfect. Can you tell me why I can't access via the generated ssh. It took me over a day and I'm still working on fixing it. Thanks
