### ISSUE TITLE
ssh: handshake failed 

### ISSUE THREAD

**Issue by theoeiferman** [appleboy/ssh-action#155]
I would like to push to remote server just using "password" without generating ssh key, using password from "secrets" settings in github. 

(NB : I create a github account for my server and linked it using ssh)

This is my yml file 

```
name: Django Deploy CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy to server
      # don't run locally
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          #port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull 
```

and I get :

```
======CMD======
cd ***
git pull 

 ======END======
2022/03/13 00:18:26 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

Do you know  what seems to be the issue ?  attempted methods doesn't seems to be what I want. 

I connect to my server from local computer running :

```
ssh SERVER_USERNAME@LIVE_SERVER_IP
password SERVER_USER_PASSWORD
```

Thank you in advance for you help !

**Comment by ariwijayaikd** [comment]
![image](https://user-images.githubusercontent.com/80755160/158062491-7e811294-e26b-4585-b98d-d7e72f3e07fe.png)
its happen for me too

**Comment by khanhkid** [comment]
You can try like that

1. Change runs-on to latest ubuntu 
`runs-on: ubuntu-latest`

2. Did you try to use ssh-key instead of pass?
and use `key` variable for private key, I guess this one can fix your problem

3. It is not relate to ssh handshake, I updated to follow `ssh-action` document for pass the `env` into the script
```
.......
        uses: appleboy/ssh-action@master
        env: 
           PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          #port: ${{ secrets.DEPLOY_PORT }}
          envs: PROJECT_PATH
          script: |
            git -C $PROJECT_PATH pull origin main
      
```

I hope you can slove it

**Comment by ariwijayaikd** [comment]
@khanhkid 
mine was like this, did i just need to place the env or using password instead of ssh-key?

`      - name: Build on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd *
            bash .github/workflows/*.sh
`

**Comment by theoeiferman** [comment]
Hey thank you so much for you help, environnement management might did the trick ! I think I had also troubles with yml syntax and tabular (I followed this to be 100% sure : https://www.arthurkoziel.com/setting-up-vim-for-yaml/) 

But it finally worked (without ssh-key) , I put my code for @ariwijayaikd just in case 

```
name: Django Deploy CD
on: [push]
  
  env:
    PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.LIVE_SERVER_IP }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_USER_PASSWORD }}
            #port: ${{ secrets.DEPLOY_PORT }}
            envs: PROJECT_PATH
            script: |
              ls -la
              git -C $PROJECT_PATH pull origin main
```

Yours,
