### ISSUE TITLE
Error: on script tag

### ISSUE THREAD

**Issue by SaHHiiLL** [appleboy/ssh-action#158]
Am trying to use SSH action to connect to my VPS and run a docker container, but it throws an error when I try to run the job I get the following warning and a status code of `1`

```
Warning: Unexpected input(s) 'script', valid inputs are ['entryPoint', 'args', 'host', 'port', 'username', 'password', 'timeout', 'command_timeout', 'key', 'key_path', 'passphrase', 'fingerprint', 'use_insecure_cipher', 'target', 'source', 'rm', 'debug', 'strip_components', 'overwrite', 'tar_tmp_path', 'proxy_host', 'proxy_port', 'proxy_username', 'proxy_password', 'proxy_passphrase', 'proxy_timeout', 'proxy_key', 'proxy_key_path', 'proxy_fingerprint', 'proxy_use_insecure_cipher']
Run appleboy/scp-action@master
  with:
    host: ***
    username: root
    password: ***
    port: 22
    script: docker image rm ***/discord-bot-fthl:latest
  docker pull ***/discord-bot-fthl:latest
  docker run -env-file .env -d ***/discord-bot-fthl:latest .
    timeout: 30s
    command_timeout: 10m
    use_insecure_cipher: false
    rm: false
    debug: false
    strip_components: 0
    overwrite: false
    proxy_port: 22
    proxy_timeout: 30s
    proxy_use_insecure_cipher: false
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.2-8/x64
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
/usr/bin/docker run --name b31c65829714b884e1cabf16a4770278240_d3daff --label 294b31 --workdir /github/workspace --rm -e JAVA_HOME -e GRADLE_BUILD_ACTION_CACHE_RESTORED -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_PORT -e INPUT_SCRIPT -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_PASSPHRASE -e INPUT_FINGERPRINT -e INPUT_USE_INSECURE_CIPHER -e INPUT_TARGET -e INPUT_SOURCE -e INPUT_RM -e INPUT_DEBUG -e INPUT_STRIP_COMPONENTS -e INPUT_OVERWRITE -e INPUT_TAR_TMP_PATH -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_USE_INSECURE_CIPHER -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Slapbot-stewie/Slapbot-stewie":"/github/workspace" 294b31:c65829714b884e1cabf16a4770278240
tar: empty archive
tar all files into /tmp/033557237/JMgdzXuEwF.tar
exit status 1
```

## My .yml file (only the part of SSH action)

```yml
- name: upload the jar file to server
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.username }}
          password:  ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker image rm sahil2903/discord-bot-fthl:latest
            docker pull sahil2903/discord-bot-fthl:latest
            docker run -env-file .env -d sahil2903/discord-bot-fthl:latest .
```

Am I not suppose to use `script` ? really confused why I have this error. P.S. my login credentials are ok.
