### ISSUE TITLE
SSH Key Passphrase

### ISSUE THREAD

**Issue by BillChirico** [appleboy/ssh-action#16]
Hello,

How do I provide an SSH key passphrase? When adding both a key and password it throws an error that I cannot have both.

**Comment by appleboy** [comment]
Please post your YAML config.

**Comment by BillChirico** [comment]
@appleboy 

Error: `ssh.ParsePrivateKey: ssh: cannot decode encrypted private keys`

I attempted to also provide password and I received and error that I cannot pass both. I removed some of the config.

```
    - name: 'Deploy'
      uses: appleboy/ssh-action@master
      with:
        host: host
        username: username
        port: 22
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
```

**Comment by appleboy** [comment]
what is your private key format?

**Comment by BillChirico** [comment]
@appleboy 

```
-----BEGIN OPENSSH PRIVATE KEY-----
XXXX
-----END OPENSSH PRIVATE KEY-----
```

**Comment by ThibaultVlacich** [comment]
Same issue for me. My private key is the same format of @BillChirico

**Comment by appleboy** [comment]
Please provide the detail steps about how to generate the private key and put the key to your remote server.

**Comment by ThibaultVlacich** [comment]
The problem is definitely not the remote, since it's not even connecting to the remote. It's the ssh-agent of the Docker image that returns that error.
The key is generated like that, and it's working perfectly to connect to the remote when I use it on my local machine:
```
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```

**Comment by ThibaultVlacich** [comment]
I got it working, generating a key like this:
```
ssh-keygen -t rsa -b 2048 -m PEM
```
But this lower the security of the remote allowing a 2048 bits key... There's probably a configuration issue with the ssh-agent of the Docker image, or the agent is not up-to-date to accept 4096 bits keys.

**Comment by appleboy** [comment]
@ThibaultVlacich 

> ssh-keygen -t rsa -b 4096 -C "test@gmail.com"

I try to generate the new key as above but it is still working for me.

**Comment by BillChirico** [comment]
The issue is, is that it’s unable to decrypt SSH keys that have been generated with a paraphrase.

**Comment by dansteren** [comment]
When creating an ssh key it is possible to add a passphrase to make the key more secure. See the following screenshot:
<img width="692" alt="Screen Shot 2019-12-29 at 6 27 19 PM" src="https://user-images.githubusercontent.com/5455419/71565203-92243300-2a69-11ea-8552-0b8e6af5cbe8.png">
If you just hit enter it doesn't add a passphrase, which I'm guessing is what @appleboy has done. However, if you do enter a passphrase, there isn't a way to supply that to this ssh-action. I would expect to be able to do something like this in my action:

```yml
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH and do stuff
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
```
However, this action doesn't have a `passphrase` input. I think what we're all hoping for is that this input gets added.

@appleboy I'm happy to help on this, I just don't understand how your action works well enough. If there is anything I can do just let me know.

**Comment by appleboy** [comment]
@dansteren I will take it for adding `passphrase` feature.

**Comment by appleboy** [comment]
@dansteren See the following example:

```diff
  - name: ssh key passphrase
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
+     passphrase: ${{ secrets.PASSPHRASE }}
      script: |
        whoami
        ls -al
```

Try the https://github.com/appleboy/ssh-action/releases/tag/v0.0.7 version

**Comment by MouaadAitSaid** [comment]
Hello, 
I am trying to use ssh-action to connect to my EC2 instance, since i took the sshKey from the AWS console, i followed the steps but i always have tis error with both key and key_path parameters: 

![image](https://user-images.githubusercontent.com/25845183/80663450-3fe53400-8a94-11ea-96cf-a3504e402511.png)

can someone help me out ?

**Comment by appleboy** [comment]
@MouaadAitSaid Please create a new issue not post here.

**Comment by ben-joostens** [comment]
I suspect a lot of people running into this private key auth issue might have forgotten to add the public key to the `authorized_keys` file of the user they are trying to connect with, since it's counter-intuitive for a user on a server to connect to that same server.

So, to summarize:

- Make sure you're logged in with the `${{ secrets.USERNAME }}` user
- Generate a key pair `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`
- `cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys`
- Add the contents of `~/.ssh/id_rsa` as `${{ secrets.KEY }}` to github

**Comment by appleboy** [comment]
@ben-joostens I will update the documentation in READEME. Thanks.

**Comment by shnigi** [comment]
I just can't get this to work. My yml

```
name: CI
on: [push]
jobs:
   deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        env:
          passphrase: ${{ secrets.SSHKEYPASSWORD }}
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          passphrase: ${{ secrets.SSHKEYPASSWORD }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull
```
I have secrets added in the repository. I can manually login to my server and do git pull. Then I enter password and it works like it should. However github actions say:

```
err: git@github.com: Permission denied (publickey).
2020/06/24 13:21:57 Process exited with status 1
err: fatal: Could not read from remote repository.
```
So what am I doing wrong here? I expected that passphrase would input the password. Or is there something else wrong?
