### ISSUE TITLE
Environment variables are passed only to first command in script

### ISSUE THREAD

**Issue by gtirloni** [appleboy/ssh-action#166]
- This action defines the input `script` which is a single string (attempting to pass a list of commands results in error)
- When multiple commands are chained with `cmd1 && cmd2` they are passed to the container in the `INPUT_SCRIPT` environment variable
- The drone-ssh plugin reads the `INPUT_SCRIPT` env var into the `script.string` which is described as `execute single commands for github action`
- All the environment variable passed to drone-ssh are concatenated and appended to the begining of the command that will be executed, resulting in `ENV1=VAL1 ENV2=VAL2 cmd1 && cmd2` 
- `cmd2` does not get the environment variables added to its environment

**Comment by OmarSRolo** [comment]
+1

**Comment by appleboy** [comment]
```yaml
      - name: pass multiple environment
        uses: appleboy/ssh-action@v1
        env:
          FOO: "BAR"
          BAR: "FOO"
          SHA: ${{ github.sha }}
          PORT: ${{ secrets.PORT }}
        with:
          host: ${{ env.REMOTE_HOST }}
          username: linuxserver.io
          key: ${{ env.PRIVATE_KEY }}
          port: 2222
          envs: FOO,BAR,SHA,PORT
          script: |
            echo "I am $FOO, thanks"
            echo "I am $BAR, thanks"
            echo "sha: $SHA"
            echo "port: $PORT"
```
