### ISSUE TITLE
Unknown Port

### ISSUE THREAD

**Issue by legionth** [appleboy/ssh-action#168]
Hey there,

I have small problem maybe someone can help me. For some reason I get the following error (I replaced the actual IP with `<my-ip>`)

```
======CMD======
20[22](https://github.com/legionth/project/runs/7266208278?check_suite_focus=true#step:3:23)/07/09 20:52:37 dial tcp: address tcp/22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
***
# <my-ip>: unknown port
cd /var/www/project
git pull origin master
======END======
```

This is my entire Action.

```yaml
name: Deployment

on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Newest Change
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/project
            git pull origin master
```

Does anybody have an idea, why the port seems to be empty?

**Comment by legionth** [comment]
Okay I got it.

Seem like the deployment script can't work with an IPv4 address through Github Secret variables.

This does work
```yaml

name: Deployment

on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Newest Change
        uses: appleboy/ssh-action@master
        with:
          host: 127.0.0.1
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/shinydoc.me
            git pull origin master
```

This won't

```yaml

name: Deployment

on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Newest Change
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/shinydoc.me
            git pull origin master
```

In `${{ secrets.SSH_HOST }}` is the same IP address (of course not 127.0.0.1 :D) as in the deployment script.
