### ISSUE TITLE
Changing directory path

### ISSUE THREAD

**Issue by rikoz** [appleboy/ssh-action#177]
Please can we have a variable specify a path/directory to change into where script will be execued?

**Comment by Luttik** [comment]
You can simply prepend your script with the `cd <your-path>` command to do this.

**Comment by rikoz** [comment]
Ok thanks

**Comment by gjain-7** [comment]
> You can simply prepend your script with the cd <your-path> command to do this.

It doesn't work for me. For eg. 
```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on remote
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        env:
          BUILD_DIR: "~/somedir"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: |
            cd $BUILD_DIR
            touch iamhere.txt
```
This creates `iamhere.txt` in `~/` instead of `~/somedir/`
