### ISSUE TITLE
Use password and key at same time

### ISSUE THREAD

**Issue by aawnu** [appleboy/ssh-action#178]
My host requires the use of both password and ssh-key to connect, but this action does not allow it returning the following: `20***/08/16 19:04:14 can't set password and key at the same time`

Its used as follows:
```yml
name: Migration

on:
  push:
    branches:
      - master

jobs:
  ssh-migration:
    needs: phpunit
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.SSH_BASE_PATH }}/laravel
            php artisan migrate
```

**Comment by zploited** [comment]
I have the exact same problem. Have been looking for different solutions, but never found one :(
Then i came across this project, and hoped it would work, but again with no luck.

Is it going to be supported?
It is really annoying that the host requires both, but not much i can do about it

@AlexWestergaard you use simply? ;)
Did you find a solution yet?

**Comment by AlexWestergaard** [comment]
@zploited for simple hosting solutions I use Simply, yes, but mostly Digital Ocean.

I did not find a fix for this action; ended up making a cronjob that checks migrations and composer updates on the go instead.

**Comment by zploited** [comment]
ok, I have found another action that could solve it for me:
- for uploading with sftp: wangyucode/sftp-upload-action
- for running ssh commands: arygrossgarten/github-action-ssh

both can use both password and private key, and I just deployed to simply with it

**Comment by AlexWestergaard** [comment]
I don't find anything on `arygrossgarten/github-action-ssh`

**Comment by zploited** [comment]
woops, yes, I missed the g when copying ;)
Good you found out

**Comment by castilloedwin** [comment]
What you need to do is to create a new ssh-key without password, I did it like this and it worked!

**Comment by aawnu** [comment]
> What you need to do is to create a new ssh-key without password, I did it like this and it worked!

That is not really an option when the host/provider requires both.

**Comment by castilloedwin** [comment]
> 

You need to create an user that does this task (no password).

**Comment by aawnu** [comment]
> > 
> 
> You need to create an user that does this task (no password).

I am not sure if you are failing to read key words like `host` and `requires` and that its *not optional*.

**Comment by castilloedwin** [comment]
Doesn't your host let you to create Linux users? for example I have two users, the first one is to manage the server and the second one for github actions and without set a password to get into, just **ssh-key** (with limited permissions).

**Comment by aawnu** [comment]
> Doesn't your host let you to create Linux users? for example I have two users, the first one is to manage the server and the second one for github actions and without set a password to get into, just **ssh-key** (with limited permissions).

Correct, the host is not a VPS and is a single-user predefined username+password. I can add key through dashboard for ssh - but it still requires both username and password on authentication.

Thus, I need it to support all 3 at once.

**Comment by castilloedwin** [comment]
Yeah, I got it, that's the problem because of **appleboy** cannot type the password (when the terminal prompt shows up) like a human. I had the same problem, for that reason I decided to create a no password new user.

**Comment by appleboy** [comment]
I will take a look.

**Comment by appleboy** [comment]
try v0.1.8 version

```yml
    - name: correct password but wrong key
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: "1234"
        port: ${{ secrets.PORT }}
        script: whoami

    - name: wrong password but correct key
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: "abcdef"
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
```
