### ISSUE TITLE
Execute local script over ssh

### ISSUE THREAD

**Issue by davegravy** [appleboy/ssh-action#186]
I have a bash script (.sh file) on my Github runner that I want to be executed on a remote host via SSH. I see that I can pass discrete commands using ssh-action, but how can an entire file be executed?

This would be similar to `ssh user@hostname < my-local-script.sh`

**Comment by devvspaces** [comment]
hi, i think you should be able to upload it on your github repository, so you can pull it on the server and run it

**Comment by devvspaces** [comment]
1. place .sh file on repo
2. ssh-action into the server
3. pull repo on the server
4. run .sh script

instead of step 3 i think you can also download the file to the server using  the absolute download link from github repo.
That would be better, instead of pulling an entire git repo

**Comment by brianjmurrell** [comment]
It's also really ugly to try to write more than a few lines of `sh` script in that `script:` tag, which has to be written as if it were all on a single line with `;` between commands, etc.  That script code cannot be linted for example.  If it cout be put into a file instead and the file executed with a `<` style redirection much of this problem goes away.

**Comment by brianjmurrell** [comment]
For those really wanting to be able to keep scripts in a separate file, there is this (admittedly ugly) hack:

```yaml
      - name: Read script contents
        id: script
        uses: andstor/file-reader-action@v1
        with:
          path: script/that/lives/in/workspace.sh
      - name: Execute local script
        uses: appleboy/ssh-action@master
        with:
          host: foo-240
          username: root
          key: ${{ secrets.POC }}
          script: ${{ steps.script.outputs.contents }}
```
