### ISSUE TITLE
Unable to run multiple commands on windows servers

### ISSUE THREAD

**Issue by MageshSrinivasulu** [appleboy/ssh-action#189]
Unable to run multiple commands on windows server. Only the first command is getting executed.

```
      - name: SSH to Windows Node
        uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8 # master hash on July 12, 2021 (newer than v0.1.4)
        continue-on-error: true
        with:
          script: |
            powershell.exe
            $service = Get-Service twistlockDefender -ErrorAction SilentlyContinue
            $script={ if ("$args[0]" -match "Running") { echo 'Service Already Installed' } else { echo 'Service Installation Needed' }}
            powershell.exe -Command $script -args $service.status           
          host: << HOST_IP >>
          username: << HOST_USERNAME >>
          password: << HOST_PASSWORD >>
```

![image](https://user-images.githubusercontent.com/79187874/194806235-c4131690-89b6-47bc-acc8-5bed4128ad6f.png)

**Comment by mmandel-bwc** [comment]
I have the same issue

**Comment by AlexCR97** [comment]
I also have this issue and cannot resolve it.

**Comment by Xavier9896** [comment]
```yml
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }} & tar -xf "dist.zip" -C "${{ secrets.DEPLOY_PATH }}" & robocopy "${{ secrets.DEPLOY_PATH }}/.vitepress/dist" "${{ secrets.DEPLOY_PATH }}" /mov /e & del /f /q "dist.zip" & rd /s /q ".vitepress"
```
Use & to concatenate commands.It works for me.
