### ISSUE TITLE
ssh into play-with-docker.com  

### ISSUE THREAD

**Issue by foremtehan** [appleboy/ssh-action#190]
When i want to ssh into an instance of play-with-docker.com with this config:

```
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: ssh key passphrase
        uses: appleboy/ssh-action@master
        with:
          host: direct.labs.play-with-docker.com
          username: ip172-18-0-018-cd3jsnm1tccg00b3sbjg
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          script: |
            docker composer up -d --build
```

I'll get the following error:

```
======CMD======
docker composer up -d --build

======END======
err: Connecting to 20.228.211.183:8022
out: 
out: 
err: 
err: 
2022/10/14 14:20:49 wait: remote command exited without exit status or exit signal
err: 
err: 
err: 
err: 
out: 
err: 
out: 
out: 
out: 
out: 
out: 
err: 
out: 
err: 
out: 
out: 
err: 
out: 
out: 
err: 
err: 
err: 
err: 
err: 
err: 
err: 
out: 
out: 
err: 
out: 
out: 
err: 
out: 
err: 
out: 
err: 
err: 
```

What is the problem here ?
