### ISSUE TITLE
SSH Key doesn't work

### ISSUE THREAD

**Issue by Chathula** [appleboy/ssh-action#2]
tried to use ssh private key. below way. copy the key and put it into the secrets. 

`cat ~/.ssh/id_rsa`

```yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@v0.0.2
      with:
        args: > 
          --host ${{ secrets.NODE_SERVER }} --user ${{ secrets.SSH_USER }} --ssh-key ${{ secrets.SSH_KEY }}
          --script 'whoami'  
```

i am getting this error

```
2019/09/19 12:12:55 ssh.ParsePrivateKey: ssh: no key found
2019/09/19 12:12:55 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```
