### ISSUE TITLE
Cannot find and kill process with lsof

### ISSUE THREAD

**Issue by jackchuong** [appleboy/ssh-action#203]
Hi, what I'm trying to do: 
```
      - name: Rerun myapp
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            lsof -n -i :3000 | grep LISTEN | awk '{print $2}' | xargs kill
            nohup node myapp/dist/main > nohup.out 2> nohup.err < /dev/null &
```
I get error: 
```
======END======
err: bash: lsof: command not found
err: bash: line 1: lsof: command not found
err: kill: not enough arguments
```
Is there anyway to fix it ?
