### ISSUE TITLE
Bash script doesn't see environment variables

### ISSUE THREAD

**Issue by Di-Mon** [appleboy/ssh-action#206]
Bash script doesn't see environment variables

I am passing env variable in main.yml

```
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          TELEBOT_TEST: "TT"
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}
          envs: TELEBOT_TEST
          script: | echo $TELEBOT_TEST
                      /home/dimon/playground/server_scripts/echo_env_variable.sh
```
Echo command show the variable, but same echo in the script doesn't:
```
Run appleboy/ssh-action@master

======CMD======
echo $TELEBOT_TEST
/home/***/playground/server_scripts/echo_env_variable.sh

======END======
out: TT
out: TELEBOT_TEST: 
==============================================
✅ Successfully executed commands to all host.
==============================================
```
Here is the script code:
```
#!/bin/bash
echo "TELEBOT_TEST: $TELEBOT_TEST"
```
