### ISSUE TITLE
SSH Unable to Authenticate

### ISSUE THREAD

**Issue by LuxxeOfficial** [appleboy/ssh-action#207]
Hello, I am making this issue because of the error: `ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain`.

**I am sure it's not an issue with the SSH keys, as I can connect to the VPS just fine using the private key I generated.**

Code:
```yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Push

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build --if-present
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: ${{secrets.PRIVATE_KEY}}
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        script: |
          pm2 delete all
          cd /var/folder
          git pull
          npm install
          pm2 start npm -- start
```

Thanks for any and all help!
