### ISSUE TITLE
Unable to execute docker command

### ISSUE THREAD

**Issue by tomekbielaszewski** [appleboy/ssh-action#210]
When I use the ssh Github Action I'm unable to execute some commands. I get results like these executables did not exist on my server.

I have the action set up like that: 

```
uses: appleboy/ssh-action@v0.1.7
with:
  host: ${{ secrets.IP }}
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}
  script: |
    which docker
    docker --version
```

When I execute these commands on my server by ssh'ing manually from my home laptop and using exactly the same user - I will get the following result:

```
~$ which docker
/usr/local/bin/docker
~$ docker --version
Docker version 20.10.3, build 55f0773
```

but when I execute exactly the same commands, from Github Action above, I get:

```
======CMD======
which docker
docker --version

======END======
2023/01/08 20:49:04 Process exited with status 127
err: sh: line 1: docker: command not found
```

I saw similar issues reported by other people in the Issues section already.
