### ISSUE TITLE
v0.1.7 Connecting to 127.0.0.1 instead of specified input variable?

### ISSUE THREAD

**Issue by huedaya** [appleboy/ssh-action#212]
This just happened a few hours ago. I suspect this because of yesterday's update.

![image](https://user-images.githubusercontent.com/4969689/211259995-f622aed8-561b-48e9-9e14-ce863070e37b.png)

This is what my code looks like 
```
      - name: Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            echo 'test'
```
