### ISSUE TITLE
issue with git pull in v.0.1.7

### ISSUE THREAD

**Issue by macelux** [appleboy/ssh-action#214]
Here is my .yml file 

 ```
steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www
            git pull origin main
```

I get merge conflicts on the server for some reasons that I don't know. I have had to downgrade to `v.0.1.4` for it to work.
