### ISSUE TITLE
Envs: variable is returning an empty string on host bash

### ISSUE THREAD

**Issue by Chanzudl** [appleboy/ssh-action#215]
Here is my sample yaml file
```

        name: SSH into the server
        uses: appleboy/ssh-action@v0.1.7
        env:
          instrument: "Piano"
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USR}}
          port: ${{secrets.PORT}}
          password: ${{secrets.PASS}}
          envs: instrument
          script_stop: true
          script: |
            cd /home/ad2cf0b5
            echo "He plays $instrument"
```
My output is 
![image](https://user-images.githubusercontent.com/94370188/211844043-28085b91-5c1f-4b81-ba22-8d44dd785328.png)
