### ISSUE TITLE
Unable to find image 'xxx' locally

### ISSUE THREAD

**Issue by vinigfer** [appleboy/ssh-action#221]
Definition on .yml file
```
    - name: Run Integration tests inside DO machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ needs.create_machine.outputs.ip_address }}
        username: user
        password: ${{ needs.create_machine.outputs.password }}
        port: "22"
        command_timeout: "10m"
        script: |
          ...
          behave
```

Github runner (self-hosted) execution logs.
```
Run appleboy/ssh-action@master
  with:
    host: 165.22.46.79
    username: root
    password: 4104875461
    port: 22
    command_timeout: 30m
    script: ...
  behave
  
    sync: false
    use_insecure_cipher: false
    timeout: 30s
    proxy_port: 22
    proxy_timeout: 30s
    proxy_use_insecure_cipher: false
    script_stop: false
    debug: false
/usr/bin/docker run --name b6a546229854e12cc4a6fa2299d5c22188802_b8d045 --label 4b6a54 --workdir /github/workspace --rm -e "INPUT_HOST" -e "INPUT_USERNAME" -e "INPUT_PASSWORD" -e "INPUT_PORT" -e "INPUT_COMMAND_TIMEOUT" -e "INPUT_SCRIPT" -e "INPUT_PASSPHRASE" -e "INPUT_SYNC" -e "INPUT_USE_INSECURE_CIPHER" -e "INPUT_CIPHER" -e "INPUT_TIMEOUT" -e "INPUT_KEY" -e "INPUT_KEY_PATH" -e "INPUT_FINGERPRINT" -e "INPUT_PROXY_HOST" -e "INPUT_PROXY_PORT" -e "INPUT_PROXY_USERNAME" -e "INPUT_PROXY_PASSWORD" -e "INPUT_PROXY_PASSPHRASE" -e "INPUT_PROXY_TIMEOUT" -e "INPUT_PROXY_KEY" -e "INPUT_PROXY_KEY_PATH" -e "INPUT_PROXY_FINGERPRINT" -e "INPUT_PROXY_CIPHER" -e "INPUT_PROXY_USE_INSECURE_CIPHER" -e "INPUT_SCRIPT_STOP" -e "INPUT_ENVS" -e "INPUT_DEBUG" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --network github_network_9ac1f851f84c44d29677451cf5c4a103 -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/data/runner1/actions-runner/_work/_temp/_github_home":"/github/home" -v "/data/runner1/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/data/runner1/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/data/runner1/actions-runner/_work/manager/manager":"/github/workspace" 4b6a54:6229854e12cc4a6fa2299d5c22188802
Unable to find image '4b6a54:6229854e12cc4a6fa2299d5c22188802' locally
docker: Error response from daemon: pull access denied for 4b6a54, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
