### ISSUE TITLE
Looks loke ssh-action connection problem after the recent update

### ISSUE THREAD

**Issue by 3JIou-home** [appleboy/ssh-action#228]
After the recent update which added the ability to specify both password and key simultaneously, I'm facing issues with ssh-action while connecting to the host using only the key.   

Workflow example:

```
- name: Execute remote command on aptly
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.APTLY_HOST }}
    username: ${{ secrets.APTLY_SSH_USER }}
    key: ${{ secrets.APTLY_SSH_PRIVATE_KEY }}
    script: |
      scp -o "StrictHostKeyChecking=no" /runner/_work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/target/debian/*${{ steps.get_version.outputs.VERSION }}*\.deb ${{ secrets.APTLY_SSH_USER }}@${{ secrets.APTLY_HOST }}:${{ secrets.APTLY_REMOTE_DIR }}
      ssh -o "StrictHostKeyChecking=no" ${{ secrets.APTLY_SSH_USER }}@${{ secrets.APTLY_HOST }} "aptly-package -d focal,stretch,jessie,buster,xenial,bionic -r foo /opt/aptly/import/${{ env.REPO_NAME }}_*${{ steps.get_version.outputs.VERSION }}_*\.deb” 
```

Error message:    

```
err: Permission denied, please try again.
err: Permission denied, please try again.
err: ***@***: Permission denied (publickey,password).
err: lost connection
err: Permission denied, please try again.
err: Permission denied, please try again.
err: ***@***: Permission denied (publickey,password).
2023/03/03 02:55:45 Process exited with status 255
```

Steps to reproduce:

Add ssh-action to your workflow and use the latest version.
Specify only the key for authentication.
Execute the workflow.
Expected behavior:
ssh-action should connect to the host using the key provided in the workflow.

Actual behavior:
ssh-action is unable to connect to the host using the key provided in the workflow and throws an error.

Note:
This issue is occurring only when using ssh-action with key authentication.
