### ISSUE TITLE
 Error response from daemon: pull access denied for act-appleboy-ssh-action-master-dockeraction, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by EduardsE** [appleboy/ssh-action#230]
Has anyone gotten this working with `act`? I'm getting this weird error.
```
Error response from daemon: pull access denied for act-appleboy-ssh-action-master-dockeraction, 
repository does not exist or may require 'docker login': denied: requested access to the 
resource is denied
``` 

```
name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: [username]
          password: [token]

      - name: Install Backend packages
        uses: appleboy/ssh-action@master
        with:
          host: [ip address]
          username: [username]
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            which docker
```

**Comment by 1Tian-zhang** [comment]
i have the same error in act, but succeed in github push action

**Comment by BartDrown** [comment]
It is because those are different layers, docker in docker/login-action isn't executed on ssh machine
Login to container registry must be done on its own, I did solve it using following command:
```
script: |
    echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u github.actor --password-stdin 

```

**Comment by appleboy** [comment]
See the example below.

```yaml
    - name: login GitHub Container Registry
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u github.actor --password-stdin

    - name: login DockerHub Container Registry
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

```
