### ISSUE TITLE
No content log to handle

### ISSUE THREAD

**Issue by didaputraa** [appleboy/ssh-action#231]
How to get content **steps.id.outputs** from log after scripts running ?

**Comment by xia-2** [comment]
I have the same question. Now, I only can know it run sucess，but can't know the running log.
<img width="744" alt="image" src="https://github.com/appleboy/ssh-action/assets/48372256/93f4ea72-570d-4c31-9f69-b9f3adb2613a">

How can I get the CMD log in the github action？

my workflow yml config:
```yml
name: deploy

on:
  workflow_dispatch: 
jobs:
  connect-and-run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Windows Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_PORD }}
          port: ${{ secrets.SERVER_PORT_PROD }}
          username: ${{ secrets.SERVER_USERNAME_PROD }}
          password: ${{ secrets.SERVER_PASSWORD_PROD }}
          script: |
            :: RUN CODE IN WINDOWS
            cd C:\Users\Administrator\spider-nest
            dir

            :: PULL CODE
            git pull
            echo ---------[END] git pull---------

            :: INSTALL DEPENDENCIES
            npm install --production=false
            echo ---------[END] npm install --production=false---------

            :: BUILD CODE
            npm run build
            echo ---------[END] npm run build---------

            :: RELOAD PM2
            pm2 reload main
            echo ---------[END] pm2 reload main---------
```
