### ISSUE TITLE
git pull returns Permission denied (publickey) 

### ISSUE THREAD

**Issue by bitrixdevelop** [appleboy/ssh-action#232]
Hello!
I wanted to automatically pulling changes on the dev server after the push. 

My action:

> name: Remote SSH
> on:
>   - push
> jobs:
>   build:
>     name: Build
>     runs-on: ubuntu-latest
>     steps:
>       - name: executing remote ssh commands using password
>         uses: appleboy/ssh-action@master
>         with:
>           host: ${{ secrets.IP }}
>           username: ${{ secrets.USER }}
>           password: ${{ secrets.PRIVATE_KEY }}
>           port: ${{ secrets.PORT }}
>           script: |
>             ${{ secrets.SCRIPT }}

The SCRIPT contains the following commands:

> cd /home/project
> git pull origin master

When I run the action, I get the following message:

> ======END======
> err: git@github.com: Permission denied (publickey).
> err: fatal: Could not read from remote repository.
> err: Please make sure you have the correct access rights
> err: and the repository exists.
> 2023/03/14 15:17:10 Process exited with status 1

The action connects under root. If I run the same commands manually under it, then there is no error, the pool is successful. Help me please!

**Comment by BlackRandomCraft** [comment]
maybe u change `steps.password` to `steps.key`?

**Comment by bitrixdevelop** [comment]
I tried, but nothing happened

**Comment by AntonioKichaev** [comment]
if u use git like ssh, i recommend u remove passphrase
```bash
ssh-keygen -p -f ~/.ssh/id_rsa
```
and leave field passphrame empty
this worked for me, try to do this

**Comment by appleboy** [comment]
Please add your private key to deploy keys page as below

![image](https://user-images.githubusercontent.com/21979/231687294-416706ef-3365-4121-bbac-bb4441fda0c4.png)

```yaml
    - name: pull private repository
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          git clone git@github.com:go-training/self-runner.git test_repository2
          cd test_repository2 && git pull
          rm -rf test_repository2
```

It is working for me. See the [output log](https://github.com/appleboy/ssh-action/actions/runs/4686523107/jobs/8304878726)

![image](https://user-images.githubusercontent.com/21979/231687785-a906eff9-57cb-4dcb-b2a5-32c8c6813860.png)

**Comment by aktienautobahn** [comment]
It is not allowed to add private key to the deploy key page, as you wrote, because : "Key is invalid. You must supply a key in OpenSSH public key format".

I can pull manually without password: my SSH-authentification works.

But with this github actions does not:

I can perform ssh commands but not authenticate with github:

err: Cloning into 'personal-site'...
err: git@github.com: Permission denied (publickey).
err: fatal: Could not read from remote repository.
err: Please make sure you have the correct access rights
err: and the repository exists.

My shortened config file:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        # Don't forget to add environment vars as secrets in repository settings on GitHub
        with:
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          # VPS username
          username: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          key: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          port: ${{ secrets.VPS_SSH_PORT }}
          # passphrase
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            git clone git@github.com:<github_name>/personal-site.git personal-site
            cd personal-site && git pull
            make build

**Comment by brunopinna** [comment]
@appleboy this is still happening and suggesting to add the private key as deploy key is not a solution, as already mentioned by @aktienautobahn deploy keys must be public keys.

![image](https://github.com/appleboy/ssh-action/assets/97514037/3ad7d58c-1d8c-4f1c-9f49-ac45267ff729)

@aktienautobahn did you find a proper solution for this issue? I'm stuck since hours. Running the pull from my VPS has no issue at all.

**Comment by webbyus** [comment]
> git pull origin master

If its success , why it shows "err Cloning into ...."

**Comment by webbyus** [comment]
> Please add your private key to deploy keys page as below
> 
> ![image](https://user-images.githubusercontent.com/21979/231687294-416706ef-3365-4121-bbac-bb4441fda0c4.png)
> 
> ```yaml
>     - name: pull private repository
>       uses: appleboy/ssh-action@v0.1.10
>       with:
>         host: ${{ secrets.HOST }}
>         username: ${{ secrets.USERNAME }}
>         key: ${{ secrets.DEPLOY_SSH_KEY }}
>         port: ${{ secrets.PORT }}
>         script_stop: true
>         script: |
>           git clone git@github.com:go-training/self-runner.git test_repository2
>           cd test_repository2 && git pull
>           rm -rf test_repository2
> ```
> 
> It is working for me. See the [output log](https://github.com/appleboy/ssh-action/actions/runs/4686523107/jobs/8304878726)
> 
> ![image](https://user-images.githubusercontent.com/21979/231687785-a906eff9-57cb-4dcb-b2a5-32c8c6813860.png)

If its success , why it shows "err Cloning into ...."

**Comment by lkp-k** [comment]
same, why does it show err?

So confusing

**Comment by lkp-k** [comment]
same, why does it show err?

So confusing

@appleboy

**Comment by alejandroaquintero** [comment]
> Please add your private key to deploy keys page as below
> 
> ![image](https://user-images.githubusercontent.com/21979/231687294-416706ef-3365-4121-bbac-bb4441fda0c4.png)
> 
> ```yaml
>     - name: pull private repository
>       uses: appleboy/ssh-action@v0.1.10
>       with:
>         host: ${{ secrets.HOST }}
>         username: ${{ secrets.USERNAME }}
>         key: ${{ secrets.DEPLOY_SSH_KEY }}
>         port: ${{ secrets.PORT }}
>         script_stop: true
>         script: |
>           git clone git@github.com:go-training/self-runner.git test_repository2
>           cd test_repository2 && git pull
>           rm -rf test_repository2
> ```
> 
> It is working for me. See the [output log](https://github.com/appleboy/ssh-action/actions/runs/4686523107/jobs/8304878726)
> 
> ![image](https://user-images.githubusercontent.com/21979/231687785-a906eff9-57cb-4dcb-b2a5-32c8c6813860.png)

Can not add a private key as a deploy key 

![image](https://github.com/appleboy/ssh-action/assets/146980342/8c57fd4a-a8f0-4d1f-95bb-3f7dd0faa6bc)

**Comment by JosefSaltz** [comment]
Also running into this issue, not sure if there's been a revision to how GH handles Deploy Keys specifically. I guess work around is to use regular repo secrets?

**Comment by viniciusaugutisps** [comment]
Same problem here.

**Comment by blekmus** [comment]
I had the same problem. Only solution was to start the `ssh-agent` and add the private key.

``` yml
name: Deploy App
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: remote execution
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: |
          eval `ssh-agent -s`
          ssh-add ~/.ssh/git_id_rsa
          cd ${{ secrets.PATH}} 
          git pull
```
