### ISSUE TITLE
`script_stop = true` - does not stop script after first failure

### ISSUE THREAD

**Issue by jpdoria** [appleboy/ssh-action#233]
Hi,

We have a step in our deployment pipeline that needs to be stopped right away on failure. I saw there's a `script_stop` option so I'm following the [Stop script after first failure](https://github.com/appleboy/ssh-action#stop-script-after-first-failure) example and I applied it on my test pipeline but it doesn't seem to work - the step still runs after failing and pipeline has been running for an hour now. Could you please help me resolve this? I'm using this `appleboy/ssh-action@v0.1.8`. Thanks so much!
![image](https://user-images.githubusercontent.com/22461427/228341845-73549548-3147-42ee-a3a2-1d3928616cba.png)
![image](https://user-images.githubusercontent.com/22461427/228341872-29011785-1174-4979-904e-ba63855f5ce0.png)

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@jpdoria Please post your console log. The following is my testing log:

![image](https://user-images.githubusercontent.com/21979/229725285-d2f13bb4-a376-49b6-ab04-d6e3295d8d08.png)

**Comment by jpdoria** [comment]
@appleboy here's the post log:

![image](https://user-images.githubusercontent.com/22461427/229726627-ba47a339-db94-41d1-b579-cc3a989a7642.png)

In your test result above, were you also using `script_stop: true` and `sync: true`?

**Comment by appleboy** [comment]
![image](https://user-images.githubusercontent.com/21979/229727894-47b2ed16-ee4c-4232-bb3f-05a39cee3628.png)

```yaml
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          mkdir abc/def
          ls -al
```
