### ISSUE TITLE
ssh connect error

### ISSUE THREAD

**Issue by BlackRandomCraft** [appleboy/ssh-action#236]
action:
```yaml
name: Deploying on a server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setting Dependencies
      run: yarn install
    - name: Assembly and deployment
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/pterodactyl
          yarn build:production
```
error:
```
2023/04/01 09:28:36 ssh.ParsePrivateKey: ssh: no key found
2023/04/01 09:28:37 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```
