### ISSUE TITLE
Error: missing server host

### ISSUE THREAD

**Issue by minhkhoablieu** [appleboy/ssh-action#239]
Can you help me.
I followed the instructions but got a Error: missing server host.

**Attachment**

![image](https://user-images.githubusercontent.com/12608657/230751299-fc54e588-bb0e-46eb-995f-5888fd219bb4.png)
![image](https://user-images.githubusercontent.com/12608657/230751315-a29bf4c2-c3e3-46c7-a930-c2b05d08b527.png)

**Comment by betowebti** [comment]
I got the same error

**Comment by aghosh0605** [comment]
I am getting same error too

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@betowebti  @betowebti  @aghosh0605 Don't use env. Replace with 

```diff
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.9
-     env:
+     with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
```

**Comment by PiotrBracha** [comment]
I use:
```        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ANSIBLE_MANAGEMENT_IP }}
          username: ${{ secrets.ANSIBLE_MANAGEMENT_USER }}
          key: ${{ secrets.ANSIBLE_MANAGEMENT_SSH_KEY }}
          script: |
```
debug logs shows:
```##[debug]Evaluating: secrets.ANSIBLE_MANAGEMENT_SSH_KEY
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ANSIBLE_MANAGEMENT_SSH_KEY'
##[debug]=> null
##[debug]Result: null

[...]
2025/02/05 13:10:37 Error: missing server host
##[debug]Docker Action run completed with exit code 1
```

Somehow secret with ssh key is evaluated as "null". In another repository I also use the same part:
```
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ANSIBLE_MANAGEMENT_IP }}
          username: ${{ secrets.ANSIBLE_MANAGEMENT_USER }}
          key: ${{ secrets.ANSIBLE_MANAGEMENT_SSH_KEY }}
          script: |
```
and there is no problem.
