### ISSUE TITLE
Issue with "diffie-hellman-group-exchange-sha256" - "handshake failed: ssh: no common algorithm for key exchange;"

### ISSUE THREAD

**Issue by harnerdesigns** [appleboy/ssh-action#245]
Hello, 

I'm trying to use the ssh-action action to modify some things on my server. I can connect to the server fine through SSH on the command line so the key works. However, when I run the action with the same key, it outputs the error: 

```
handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 diffie-hellman-group14-sha1 ext-info-c], server offered: [diffie-hellman-group-exchange-sha256]
```

Per issue #56, I added the `use_insecure_cipher: true` option, but then that gives me the error: 

```
2023/04/24 19:00:16 ssh.ParsePrivateKey: asn1: structure error: length too large
2023/04/24 19:00:16 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

Which I'm assuming means I need to regenerate the SSH key, but it's throwing me off that the key works fine when just directly SSH-ing through the command line, but doesn't work here. 

Config:

```
    steps:
    - name: Run Backup Script
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd /var/www/***
          ./***
```

Any help or insight here would be greatly appreciated!
