### ISSUE TITLE
‘node’: No such file or directory

### ISSUE THREAD

**Issue by ArthurPedroti** [appleboy/ssh-action#246]
I always use the same script and now starts to give me this error. Does anyone have an idea about what I can do?

Input:
```
- name: Run production scripts
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    port: ${{ secrets.SSH_PORT }}
    password: ${{ secrets.SSH_PASS }}
    script: pm2 restart quartz-api
```

Output:
```
======CMD======
pm2 restart quartz-api
======END======
err: /usr/bin/env: ‘node’: No such file or directory
Process exited with status 127
```
