### ISSUE TITLE
Connection Error: dial tcp: no such host

### ISSUE THREAD

**Issue by lukewyman** [appleboy/ssh-action#250]
Deployed an AWS EC2 instance as a bastion host using Terraform in my workflow. I'm getting this error, even though the instance is fully initialized and I am able to SSH into it from my laptop with both public dns and public ip. I've tried both public dns and public ip in the workflow step. I've also tested that `steps.tf_outputs.outputs.bastion_public_ip` contains the value I expect.

```
- name: Setup up data directory on bastion
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ steps.tf_outputs.outputs.bastion_public_ip }}
          username: ubuntu
          port: 22 
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            rm -rf /home/user/test_data
            mkdir /home/user/test_data
```

And here is the error:
```
======CMD======
rm -rf /home/user/test_data
mkdir /home/user/test_data

======END======
2023/05/16 01:[34](https://github.com/lukewyman/bastions-tunnels-and-keys/actions/runs/4986881720/jobs/8928113920#step:12:35):44 dial tcp: lookup "54.218.162.46": no such host
```
