### ISSUE TITLE
dial tcp ***:3971: i/o timeout

### ISSUE THREAD

**Issue by yavda1** [appleboy/ssh-action#253]
Hey, I'm trying to deploy my node.js app and am encountering this error

`2023/06/08 01:10:16 dial tcp ***:3971: i/o timeout`

I have this in my cd.yml
```
name: FunkyBot CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: 3971
        script: |
          cd /home/ubuntu/discord/funkybot
          git pull origin main
          git status
          npm install --only=prod
          pm2 restart funkybot
          
```
and this in my ci.yml
```
name: FunkyBot CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 19
      uses: actions/setup-node@v2
      with:
        node-version: 19.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
```
this is my output:

<img width="1844" alt="Screen Shot 2023-06-07 at 6 17 05 PM" src="https://github.com/appleboy/ssh-action/assets/94653933/1e721ecd-bf08-413c-8295-09b810e40a68">
