### ISSUE TITLE
How can I do it with multiple hosts with different keys?

### ISSUE THREAD

**Issue by lamhktommy** [appleboy/ssh-action#256]
My yaml file is like this 
```
- name: Pull and run container in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
           docker pull .... 
           docker run ...
```
I can set HOST=a.com,b.com as i read the documentation but i am not sure how can i do with a.com using A.key and b.com using B.key

PS. SSH_KEY is the full file content of the key file.
