### ISSUE TITLE
trying to pass Environment variable to set oracle_home

### ISSUE THREAD

**Issue by prasantabarik** [appleboy/ssh-action#257]
Hello, I am using 

     -name: executing remote ssh commands using ssh key
       env:
         ORACLE_HOME=/ora/product/db/19000
         LD_LIBRARY_PATH=/ora/product/db/19000/lib
         PATH=/ora/product/db/19000/bin 
       uses: appleboy/ssh-action@v0.1.10
       with:
        host: ${{ secrets.HOST_TEST }}
        username: ${{ secrets.USER_TEST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
       envs: ORACLE_HOME,LD_LIBRARY_PATH,PATH
        script: |
          export ORACLE_HOME=$ORACLE_HOME
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
          export PATH=$PATH  
          sqlplus

getting the below result 

![image](https://github.com/appleboy/ssh-action/assets/54621979/0886225e-68d5-4eba-800a-67cd026e428f)

**Comment by prasantabarik** [comment]
Hello @appleboy , could you help looking into this issue ?

**Comment by appleboy** [comment]
@prasantabarik You should try the following config:

```yaml
 -name: executing remote ssh commands using ssh key
   env:
     ORACLE_HOME=/ora/product/db/19000
     LD_LIBRARY_PATH=/ora/product/db/19000/lib
     EXEC_PATH=/ora/product/db/19000/bin 
   uses: appleboy/ssh-action@v0.1.10
   with:
    host: ${{ secrets.HOST_TEST }}
    username: ${{ secrets.USER_TEST }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
   envs: ORACLE_HOME,LD_LIBRARY_PATH,EXEC_PATH
    script: |
      export ORACLE_HOME=$ORACLE_HOME
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
      export PATH=$PATH:$EXEC_PATH
      sqlplus
```

Don't overwrite your `PATH` with single PATH.
