### ISSUE TITLE
Error: missing server host

### ISSUE THREAD

**Issue by 2044smile** [appleboy/ssh-action#263]
`github.actions.yml`
```
name: AWS EC2 Automated Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/code/backend
            git pull origin main
            sudo systemctl restart gunicorn
```

I am using master version and I am using AWS .pem key and AWS Security Group port 22 is open

```
-----BEGIN RSA PRIVATE KEY-----
****
-----END RSA PRIVATE KEY-----
```

Why does 'Error: missing server host error' appear? Help me
