### ISSUE TITLE
Error: missing server host

### ISSUE THREAD

**Issue by EncryptEx** [appleboy/ssh-action#267]
Hi! 
Yesterday I started experiencing some failures on my CI and I realized that it was giving me the error: 
``Error: missing server host``
But, my GitHub actions yml [file] (https://github.com/EncryptEx/hammer/blob/master/.github/workflows/deploy.yml) appears to be nice.
I don't know exactly what's happening, since I haven't changed anything from the secrets page.

**Comment by EncryptEx** [comment]
Reran with debug enabled: https://github.com/EncryptEx/hammer/actions/runs/5973324023/job/16207683305

**Comment by lukynmatuska** [comment]
I got same problem with my projects (https://github.com/lukynmatuska/vvcb-firesporteu-middleware/pull/3, https://github.com/rudickamladez/pohles-backend/pull/119)

**Comment by appleboy** [comment]
Do you have add secret in your repository?

**Comment by appleboy** [comment]
I have try the same config with my project

```yaml
    - name: update docker-compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: deploy
        key: ${{ secrets.MONITOR_KEY }}
        port: 22
```

It is working. Can you please try the real value in the `host` attribute?
