### ISSUE TITLE
Error on runtime: /entrypoint.sh: line 7: sh: not found

### ISSUE THREAD

**Issue by SzymonRysztof** [appleboy/ssh-action#269]
Hi, 
I'm trying to setup ssh workflow based on this action, but sadly, when it comes to step that is supposed to login to my host via ssh, I'm receiving 
`/entrypoint.sh: line 7: sh: not found` 
error 
It looks like action is building and then using docker container which has ssh client, but it looks like somehow base image does not have sh installed.

This is my step: 
```
steps:
      - name: Deploy develop
        env:
          PATH: ***
          COMPOSE_FILE: ***
          RELEASE: ***
        uses: appleboy/ssh-action@v1.0.0
        if: github.ref == 'refs/heads/develop'
        with:
          envs: PATH,COMPOSE_FILE,RELEASE
          host: secret
          username: secret
          key: secret
          port: secret
          script: |
            cd $PATH
            git pull
            docker-compose -f $COMPOSE_FILE pull
            docker-compose -f $COMPOSE_FILE up -d
```
But i think my config is irrelevant since it looks like base image problem (since it fails on entrypoint with sh not being available)
 
 Is there something that i'm missing? Or what steps can i take to investigate it more (if somehow error is on my part)?
