### ISSUE TITLE
Not failing properly

### ISSUE THREAD

**Issue by maxisme** [appleboy/ssh-action#27]
Hello,

My cmd that I execute is `bash /root/deploy.sh` when executing the step I get:

```
======CMD======
*** 161818ed29a100f924cb7aaa862e297d92c457d7

======END======
err: fatal: not a git repository (or any of the parent directories): .git
err: fatal: not a git repository (or any of the parent directories): .git
err: fatal: not a git repository (or any of the parent directories): .git
err: /***/***/deploy.sh: line 9: go: command not found
err: /***/***/deploy.sh: line 12: go: command not found
==============================================
✅ Successfully executed commands to all host.
==============================================
```

Why is this returned as a success when the exit code is 1?

```
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            ${{ secrets.DEPLOY_CMD }} ${{ github.sha }}
```
