### ISSUE TITLE
Switch User (su) not working

### ISSUE THREAD

**Issue by shubhenduanupamdutta** [appleboy/ssh-action#279]
```
 - name: executing ubuntu instance using ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.HOST_IP}}
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          port: 22
          script:  |
            su - ${{user}}
            whoami
```
## I have already tried going into root mode before. But it is still not working.

**Comment by appleboy** [comment]
Please see the config from `/etc/sudoers` file.

**Comment by shubhenduanupamdutta** [comment]
I was able to bypass the issue.
I am a novice in Ubuntu. So I have no idea what you want me to do with 
"Please see the config from /etc/sudoers file." instruction.
I saw the file. And then???

**Comment by outinim** [comment]
Up on this matter, I have the same issue whe trying to connect as a service account (`aboten`) on which all is configured (sudo + ssh - deploy keys):

`======CMD======
# Switch user
whoami
sudo su moutini
whoami
pwd
# Activate env
conda activate ciara_venv
`

And get this as output:
`======END======
out: aboten
err: bash: line 10: conda: command not found
out: aboten
out: /home/aboten
2024/01/05 14:17:22 Process exited with status 127`

I stay as the current user `aboten` instead of switching to user `moutini`

**Comment by outinim** [comment]
Solution founds: launch command as sudo and pipe your instructions on the fly

```bash
 sudo su - -c "whoami && echo 'hello world' && touch toto.txt
```

Returns as planned:
```bash
out: root
out: hello world
```

**Comment by appleboy** [comment]
@shubhenduanupamdutta Just add the following config to `/etc/sudoers` file

```
your_account ALL=(ALL) NOPASSWD:ALL
```

**Comment by appleboy** [comment]
Open your `/etc/sudoers` config and add the following config

```
deploy ALL=(ALL) NOPASSWD: /usr/bin/whoami
```

update script

```yaml
- name: executing ubuntu instance using ssh
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{secrets.HOST_IP}}
    username: ubuntu
    key: ${{secrets.SSH_KEY}}
    port: 22
    request_pty: true
    script:  |
      sudo whoami
```

see the example: https://github.com/appleboy/ssh-action/blob/9b978f09f2587beff9c80449f57cb0f0612d3039/.github/workflows/ci.yml#L274-L284
