### ISSUE TITLE
ssh i/i timeout

### ISSUE THREAD

**Issue by jaeilnet** [appleboy/ssh-action#280]
```
name: cd

on:
    push:
        branches:
            - 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: SSH Remote Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      echo "test"
                      ls

```

======CMD======
echo "test"
ls

======END======
23/11/20 07:05:56 dial tcp ***:***: i/o timeout

---

try

local ssh key privite key registered in repo
I don't know what's going on with i/o timeout even if I don't enter a private key.
