### ISSUE TITLE
github action run shell script err: sudo: a password is required

### ISSUE THREAD

**Issue by hendisantika** [appleboy/ssh-action#289]
github action run shell script err: sudo: a password is required.

```
      - name: Restart webapp via pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sh /var/www/portofolio/pm2.sh
```

pm2.sh
```
#!/bin/bash
# Created by Hendi Santika
# Created Date: Tuesday, Nov 14 2023 7:20 WIB GMT+7
# Visit me: https://s.id/hendisantika
if ! type pm2 > /dev/null
then
    sudo npm install pm2 && pm2 start ecosystem.config.cjs  --name "PORTOFOLIO WEB APP"
else
    pm2 restart "PORTOFOLIO WEB APP"
fi

```
