### ISSUE TITLE
Pass envs to scripts not working in v1.0.3

### ISSUE THREAD

**Issue by zvn2060** [appleboy/ssh-action#290]
I tested with the document example: 
```yml
- name: Test document example
  uses: appleboy/ssh-action@v1.0.3
  env:
    FOO: "BAR"
    BAR: "FOO"
    SHA: ${{ github.sha }}
  with:
    host: "example.com"
    envs: FOO,BAR,SHA
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    username: Username
    script: |
      echo "I am $FOO"
      echo "I am $BAR"
      echo "sha: $SHA"
```

however seems not working

```
======CMD======
echo "I am $FOO"
echo "I am $BAR"
echo "sha: $SHA"

======END======
out: I am 
out: I am 
out: sha: 
==============================================
✅ Successfully executed commands to all host.
==============================================
```

**Comment by appleboy** [comment]
I try to re-run the script. It is working on `master` branch. See the following output.

```yaml
    - name: pass multiple environment
      uses: appleboy/ssh-action@v1.0.3
      env:
        FOO: "BAR"
        BAR: "FOO"
        SHA: ${{ github.sha }}
        PORT: ${{ secrets.PORT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: FOO,BAR,SHA,PORT
        script: |
          echo "I am $FOO, thanks"
          echo "I am $BAR, thanks"
          echo "sha: $SHA"
          echo "port: $PORT"
          sh test.sh
```

https://github.com/appleboy/ssh-action/actions/runs/7437989374/job/20927724586

![image](https://github.com/appleboy/ssh-action/assets/21979/bb8e3bee-adb8-47f5-8edf-409e0393e429)
