### ISSUE TITLE
ssh.ParsePrivateKey: ssh: this private key is passphrase protected

### ISSUE THREAD

**Issue by simanacci** [appleboy/ssh-action#293]
**Workflow**
```yaml
- name: Deploy
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ vars.DROPLET_IP }}
    key: ${{ secrets.SSH_KEY }}
    port: 22
    username: sammy
    script: |
        cd ~
        export FOO=${{ secrets.FOO }} BAR=${{ secrets.BAR }}
        docker-compose down
        docker-compose pull
        docker-compose up -d
```
**File Permissions**
```terminal
sammy@ubuntu-s-1vcpu-2gb-blr1-01:~/.ssh$ stat -c "%a %n" *
600 authorized_keys
```
```terminal
sammy@ubuntu-s-1vcpu-2gb-blr1-01:~$ stat -c "%a %n" .ssh
700 .ssh
```
**sshd_config**
`cat /etc/ssh/sshd_config`
https://gist.github.com/simanacci/134c838a474fdc25433dcd91c359509e
```terminal
sammy@ubuntu-s-1vcpu-2gb-blr1-01:/etc/ssh/sshd_config.d$ ls
50-cloud-init.conf  60-cloudimg-settings.conf

sammy@ubuntu-s-1vcpu-2gb-blr1-01:/etc/ssh/sshd_config.d$ sudo cat 50-cloud-init.conf
PasswordAuthentication no

sammy@ubuntu-s-1vcpu-2gb-blr1-01:/etc/ssh/sshd_config.d$ sudo cat 60-cloudimg-settings.conf
PasswordAuthentication no
```
**Error**
```terminal
2024/02/02 18:04:17 ssh.ParsePrivateKey: ssh: this private key is passphrase protected
======CMD======
```
```terminal
======END======
2024/02/02 18:04:19 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```
Root is disabled. `sammy` is a `sudoer`. I can connect to the Droplet successfully via `ssh sammy@ip_address` without a Passphrase.
