### ISSUE TITLE
dial tcp ***:***: i/o timeout bastion host to private ec2

### ISSUE THREAD

**Issue by davidgacc** [appleboy/ssh-action#296]
Hi people,

I want to connect to my private instance ec2 from my bastion ec2(public ip) but i got:

 **dial tcp ***:***: i/o timeout bastion host to private ec2** .

Also, when i run the command from my bastion ec2: ` ssh stage`, i can join to the ec2 private instance. However in the worklow i get timeout error . Anyone could help? thanks a lot.

I followed all the steps

this is my .ssh/config on my bastion ec2
```
Host bastion
  HostName x.x.x.x
  User ubuntu
  Port 22
  IdentityFile ~/.ssh/keys/key.pem

Host stage
  HostName x.x.x.x
  User ubuntu
  Port 22
  ProxyCommand ssh -q -W %h:%p bastion
```

stage.yml

```
name: Build and Deploy

on:
  push:
    branches: [stage]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy with docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_BASTION_HOST }}
          username: ${{ secrets.SSH_USERNAME_STAGE }}
          key: ${{ secrets.SSH_KEY_STAGE }}
          port: ${{ secrets.SSH_PORT_STAGE }}
          proxy_host: ${{ secrets.SSH_HOST_STAGE }}
          proxy_username: ${{ secrets.SSH_USERNAME_STAGE }}
          proxy_key: ${{ secrets.SSH_KEY_STAGE }}
          proxy_port: ${{ secrets.SSH_PORT_STAGE }}
          script: |
            whoami
            ls -al
```

**Comment by MADEiN83** [comment]
Hi.

I'm facing the same issue on my side:

```bash
2024/02/10 07:08:14 dial tcp ***:22: i/o timeout
```

With this configuration:
```yaml
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: ...
```

I can connect to my server through `SSH` via terminal. So my server is alive 😜
