### ISSUE TITLE
Deployment completed but nothing happens on my vps

### ISSUE THREAD

**Issue by alinpr18** [appleboy/ssh-action#304]
```
name: remote ssh command
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            exec bash
            touch .env
            echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
            cd ${{ secrets.WORK_DIR_TEST }}
            git pull 
            bun install
            exit
```

![image](https://github.com/appleboy/ssh-action/assets/79379711/04295e23-dd74-4043-aa0f-fc2dbf9cade5)
