### ISSUE TITLE
Error in preparation before connecting to ssh

### ISSUE THREAD

**Issue by khamdullaevuz** [appleboy/ssh-action#306]
<img width="479" alt="image" src="https://github.com/appleboy/ssh-action/assets/81905341/fdd60933-1219-4e43-b7d8-694bb9097bf3">

How can i fix?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Same with https://github.com/appleboy/ssh-action/pull/303 comments.

**Comment by khamdullaevuz** [comment]
thank you

**Comment by appleboy** [comment]
Hi @khamdullaevuz 

I reopened the issue since the #303 issue you reported is the same as what you reported, let's discuss it here together.

**Comment by khamdullaevuz** [comment]
Hello @appleboy
Yes, I thought the bug was fixed and closed this. But the error is observed again.

**Comment by appleboy** [comment]
The following is my config

```
name: testing master
on: [push]

jobs:
  testing01:
    name: testing new bash flow
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: try bash script
        uses: appleboy/ssh-action@master
        with:
          host: 2402:1f00:8000:800::2628
          username: ubuntu
          password: ${{ secrets.OVH_PASSWORD }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            whoami
```

output:

![image](https://github.com/appleboy/ssh-action/assets/21979/87abfbea-47ab-443c-9056-9877b0e03414)

https://github.com/appleboy/ssh-action/actions/runs/8343438946/job/22833645938

You can't see the download progress?
