### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by irakli-ika** [appleboy/ssh-action#309]
Hello, I try to deploy a project with Github to Digitalocean, I use ssh-action@v1.0.3 and have this issue `***:22: i/o timeout`.
I saw old solutions with `port: 8000` but it returns the same error `***:8000: i/o timeout`, can you help me fix this issue?

**Comment by appleboy** [comment]
Please post your all workflow. Thanks.

**Comment by irakli-ika** [comment]
> Please post your all workflow. Thanks.

name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy Laravel App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir www
            cd www
            mkdir html
            cd html
            git clone https://github.com/irakli-ika/reponamehere.git

**Comment by felipe3dfx** [comment]
I have the same error:

```yml
  deploy:
    runs-on: self-hosted
    environment: production
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ github.event.repository.name }}
            git fetch
            git checkout '${{ github.sha }}'
            bash bin/main_run
```

![image](https://github.com/appleboy/ssh-action/assets/4070833/b682a16d-7d2a-48bc-bbf2-f781ce564556)
