### ISSUE TITLE
Some commands don't work

### ISSUE THREAD

**Issue by ClassyCircuit** [appleboy/ssh-action#31]
```
err: bash: -c: line 3: syntax error near unexpected token `('
2020/02/09 17:57:24 Process exited with status 1
err: bash: -c: line 3: `sudo rm -r /usr/dotnetapps/bugsincluded/!(*.db*)'
```

This is a valid linux command that removes all files and folders that don't match the pattern, it works when I run it manually on my server, but it doesn't work using this ssh-action tool.

**Comment by appleboy** [comment]
Another approach is to put your command into the shell script file and execute `sh xxxx.sh`.

**Comment by palashCItobuz** [comment]
> Another approach is to put your command into the shell script file and execute `sh xxxx.sh`.
The shell script is being able to run node js or npm commands. How can they be executed? Tried loading `. /etc/profile` in the shell script.

**Comment by mittalyashu** [comment]
Any suggestions?

```yml
      - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.hosts }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: sh ../../scripts/deploy.sh
```

If we try to execute `sh ../../scripts/deploy.sh` wouldn't it will try running inside the server where we're trying SSH into.

**Comment by mojo706** [comment]
It will in fact execute inside the vps you're trying ssh into. You could use `run` instead like this
```
- name: Executing remote command
        uses: appleboy/ssh-action@v0.1.2
        run: sh ../../scripts/deploy.sh
        with:
          host: ${{ secrets.hosts }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
```
I think that should work

**Comment by mittalyashu** [comment]
@mojo706 It shows an error saying.

```
a step cannot have both the `uses` and `run` keys
```

**Comment by mojo706** [comment]
Could you show me your whole discord job?

**Comment by mojo706** [comment]
```
steps:
    - uses: actions/checkout@master
    - run: echo ::set-env name=PR_NUMBER::$(echo ${{ github.ref }} | awk 'BEGIN { FS = "/" } ; { print $3 }')
    - name: send message to discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
```
@mittalyashu that's how I set mine up.

**Comment by mittalyashu** [comment]
@mojo706 

```yml
- name: Executing remote command
  uses: appleboy/ssh-action@v0.1.2
  env:
    BACKEND_APP_PORT: 8080
    NODE_ENV: "production"
  with:
    host: ${{ secrets.IP }}
    USERNAME: ${{ secrets.USERNAME }}
    PORT: ${{ secrets.PORT }}
    KEY: ${{ secrets.SSHKEY }}
    envs: BACKEND_APP_PORT, NODE_ENV
    script: ls
```

**Comment by mojo706** [comment]
```
  steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@v0.1.2
      env:
        BACKEND_APP_PORT: 8080
        NODE_ENV: "production"
      with:
        host: ${{ secrets.IP }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: BACKEND_APP_PORT, NODE_ENV
        script: ls
```
@mittalyashu try that

**Comment by mittalyashu** [comment]
Isn't it the exact same code which I have shared.

https://github.com/appleboy/ssh-action/issues/31#issuecomment-655275661

**Comment by mojo706** [comment]
Lol shit I forgot to change it. I guess I was tired, I wanted you to add `run` under `uses` it should work now.

**Comment by mittalyashu** [comment]
You mean something like this?

```yml
- name: Executing remote command
  uses: appleboy/ssh-action@v0.1.2
  run: echo "Running this in GitHub Action"
  env:
    BACKEND_APP_PORT: 8080
    NODE_ENV: "production"
  with:
    host: ${{ secrets.IP }}
    USERNAME: ${{ secrets.USERNAME }}
    PORT: ${{ secrets.PORT }}
    KEY: ${{ secrets.SSHKEY }}
    envs: BACKEND_APP_PORT, NODE_ENV
    script: ls
```

**Comment by appleboy** [comment]
```yaml
  with:
    host: ${{ secrets.IP }}
    username: ${{ secrets.USERNAME }}
    port: ${{ secrets.PORT }}
    key: ${{ secrets.SSHKEY }}
    envs: BACKEND_APP_PORT, NODE_ENV
    script: ls
```

**Comment by mojo706** [comment]
you need to have the `steps` keyword @mittalyashu

**Comment by bnbrndn** [comment]
Along the same lines, does anyone have a solution for cd not working? thanks

**Comment by appleboy** [comment]
@bnbrndn Post your config.

**Comment by nick339s** [comment]
I had some problem when i use root user access

**Comment by ShravaniRoy** [comment]
> Along the same lines, does anyone have a solution for cd not working? thanks

Did you find a solution @bnbrndn

**Comment by ShravaniRoy** [comment]
Only the first command works from script:
![image](https://user-images.githubusercontent.com/17310598/108761570-062a7000-7575-11eb-8a8a-a1c52a4acb1f.png)
Am I missing something??

**Comment by bnbrndn** [comment]
> > Along the same lines, does anyone have a solution for cd not working? thanks
> 
> Did you find a solution @bnbrndn

The problem I was having was I needed to CD into a directory to run composer install. The work around I found was to run "composer install -d public_html"

Not the cleanest, but it did what I needed

**Comment by suxiaolong** [comment]
with:
          host: ${{ secrets.IP2 }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD_GOOGLE }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            sudo su -
            pwd
            yum -y install git
            cd /opt/blog-vue
            git pull
第一次安装git,  第二次就可以把 yum -y install git 去掉了

**Comment by suxiaolong** [comment]
`
 with:
          host: ${{ secrets.IP2 }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD_GOOGLE }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            sudo su -
            pwd
            yum -y install git
            cd /opt/blog-vue
            git pull
`
第一次安装git 第二次就可以把yum -y install git删除了

**Comment by suxiaolong** [comment]
![](http://hexo.xiaolongsu.cn/2021-img/20210728162741.png)
第一次同步时安装git, 第二次就可以把 yum -y install git 去掉了

**Comment by MahbbRah** [comment]
This is crazy! the issue is yet not solved! I tried all different commands to run my `sh` file on remote local But it's not working, I guess it's running on a virtual docker environment. How could I run this on my remote machine?

@appleboy  Please can you help.

**Comment by kocyigityunus** [comment]
@MahbbRah 

this issue is about interactive vs non interactive shell.

you can check this at:
https://askubuntu.com/questions/247738/why-is-etc-profile-not-invoked-for-non-login-shells

basically, if you are running a command in a non interactive shell, like ssh-action, on many linux distros, 

"/etc/bash.bashrc" file has a specific command that returns only, so some of the files didn't run and some specific commands doesn't add to path,

`
#/etc/bash.bashrc
# System-wide .bashrc file for interactive bash(1) shells.

# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

# If not running interactively, don't do anything
[ -z "$PS1" ] && return`

just comment out the line that returns early and everything should work fine, or you can use the real paths of the commands that you would like to use.

**Comment by ronatory** [comment]
Thanks @kocyigityunus. The hint for using the real paths 
> or you can use the real paths of the commands that you would like to use.

works for me

**Comment by MageshSrinivasulu** [comment]
@ShravaniRoy @jgilm Were you able to overcome the issue? I am too facing a similar problem where I am not able to run multiple commands on the windows server

**Comment by ShravaniRoy** [comment]
> @ShravaniRoy @jgilm Were you able to overcome the issue? I am too facing a similar problem where I am not able to run multiple commands on the windows server

Hey Magesh, We actually moved to the ubuntu server. This worked fine on Ubuntu.

**Comment by MageshSrinivasulu** [comment]
@ShravaniRoy Thanks for the quick response. Created a separate issue for the same https://github.com/appleboy/ssh-action/issues/189

**Comment by mkosir** [comment]
Hey, went through the answers and tried different approaches  but nothing worked.
My question is how it would be possible to run my shell/bash script in separate file (my-script.sh), which is located on ext to github action file CI.yml?
```yaml
 - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.2
        with:
          ...
          script: sh ./my-script.sh
```

In other CIs or terminal where this nice appleboy/ssh-action doesnt exist, to make it work you pass your own shell script as:
```shell
ssh root@${server} 'bash -s' < ./my-script.sh 
```

**Comment by marqueetest** [comment]
Here is my config
```
      - name: Deploy source-code
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER }}
          PORT: ${{ secrets.PORRT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            sh /var/www/automation/rerun-project.sh
```

Below is my sh file
```
cd /var/www/html/my-project
git pull
npm install
forever restart project

```
            
But while action run on git hub, it is giving below error
```
err: /var/www/automation/rerun-project.sh: 3: /var/www/automation/rerun-project.sh: npm: not found
err: /var/www/automation/rerun-project.sh: 4: /var/www/automation/rerun-project.sh: forever: not found
```
Below first two command working perfectly fine but not sure why npm and forever not working. npm & forever command I am able to execute from putty.
```
cd /var/www/html/my-project
git pull
```
