### ISSUE TITLE
getKeyFile error: open key.pem: permission denied

### ISSUE THREAD

**Issue by lmilbaum** [appleboy/ssh-action#312]
The step in the workflow:
```
     - name: provisioning test environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.host.outputs.host }}
          username: fedora
          key_path: key.pem
          script: provision.sh

```
But, the following does work:
```
    - run: |
          ssh -T -o StrictHostKeyChecking=no -i key.pem fedora@${{ steps.host.outputs.host }} bash -c ls
```
