### ISSUE TITLE
Error: missing server host when called from `workflow_call`

### ISSUE THREAD

**Issue by Juknum** [appleboy/ssh-action#316]
Hi, it might be intentional (I did not see anything in the README) but I was trying to use `appleboy/ssh-action@master` trough a workflow call like so (~~for testing purpose as this use case is a no-go aha, why would you deploy on a PR~~) :

```yml
# .github/workflows/update.yml
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: PR/Push update

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/linting.yml
```

```yml
# .github/workflows/deploy.yml
name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
```

But the action failed (with the same error message as #19) without further explanation (I guess something doesn't get passed trough the call) 
- https://github.com/faithful-mods/website/actions/runs/8695308856/job/23846089666

Whereas using it directly on a push change event does work as expected:
- https://github.com/faithful-mods/website/actions/runs/8695333080/job/23846160791

**Comment by appleboy** [comment]
@Juknum Please help to try the following guide.

https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets

```yaml
on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false

jobs:

  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
    # passing the secret to an action
      - name: Pass the received secret to an action
        uses: ./.github/actions/my-action
        with:
          token: ${{ secrets.access-token }}

  # passing the secret to a nested reusable workflow
  pass-secret-to-workflow:
    uses: ./.github/workflows/my-workflow
    secrets:
       token: ${{ secrets.access-token }}
```
