### ISSUE TITLE
Unable to run bash script with master branch version

### ISSUE THREAD

**Issue by bobcoin98** [appleboy/ssh-action#317]
/usr/bin/env: ‘bash’: Permission denied
Error: Process completed with exit code 126.

Setting user to root already

**Comment by bobcoin98** [comment]
<img width="429" alt="image" src="https://github.com/appleboy/ssh-action/assets/138571486/2734c192-66e4-4aae-9f5c-882858212894">

**Comment by appleboy** [comment]
@bobcoin98 Please post your yaml config.

**Comment by bobcoin98** [comment]
reverting back to  `appleboy/ssh-action@v1.0.3` -> it works
so please check your master branch

**Comment by appleboy** [comment]
@bobcoin98 Can you post your raw data of yaml file?

**Comment by appleboy** [comment]
> if I put secrets in script like this, I got the error
> If I put plain text instead, then It works

Is that true?

**Comment by bobcoin98** [comment]
> > if I put secrets in script like this, I got the error
> > If I put plain text instead, then It works
> 
> Is that true for the master version?

yes,
for master version, error occurs if I put any secret in script

**Comment by ddjerqq** [comment]
v1.0.3 indeed works, master is broken!!!

**Comment by appleboy** [comment]
I will take a look master branch.

**Comment by EncryptEx** [comment]
Im experiencing the same issue; with @latest it gives me error, but with 1.0.3 works fine.

**Comment by appleboy** [comment]
@EncryptEx Post your config?

**Comment by EncryptEx** [comment]
Here's mine
https://github.com/EncryptEx/femtolink/blob/main/.github/workflows/deploy.yml
in both job runs i ran the same command:
sudo /path/to/file.sh

**Comment by appleboy** [comment]
@bobcoin98 

Please try the following config: use `env` attribute.

```yaml
    - name: Test command SSH
      uses: appleboy/ssh-action@master
      env:
        FOO: ${{ secrets.PATH }}
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: FOO
        script: cd $FOO
```
