### ISSUE TITLE
 script_stop: true mess up cat command

### ISSUE THREAD

**Issue by uchar** [appleboy/ssh-action#335]
## Describe the bug

When I use   `script_stop: true`  the output of the cat command becomes 
``` 
    {
              "RESTORE_BACKUP": "$RESTORE_BACKUP",
              "FTP_HOST": "$FTP_HOST",
              DRONE_SSH_PREV_COMMAND_EXIT_CODE=0 ; if [ 0 -ne 0 ]; then exit 0; fi;
             {
              DRONE_SSH_PREV_COMMAND_EXIT_CODE=0 ; if [ 0 -ne 0 ]; then exit 0; fi;
```

## Yaml Config

```yaml

      - name: Clone project and run docker
        uses: appleboy/ssh-action@master
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          RESTORE_BACKUP: ${{ github.event.inputs.restoreBackup }}
        with:
          command_timeout: 60m
          script_stop: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: FTP_HOST,RESTORE_BACKUP
          script: |
            cat <<EOF > ./inputsData/deployEnvs.json
            {
              "RESTORE_BACKUP": "$RESTORE_BACKUP",
              "FTP_HOST": "$FTP_HOST",
            }
            EOF

```

it works fine without `script_stop: true`
