### ISSUE TITLE
Pick shell

### ISSUE THREAD

**Issue by roablep** [appleboy/ssh-action#343]
## Describe the bug

I would like to be able to specify the shell used to run the scripts. Currently this is not possible and adding shebang at the top doesn't seem to work. 

## Yaml Config

Please post your Yaml configuration file along with the output results.

```yaml
          script: |
            #!/bin/bash
            required_containers=("service1" "service2")
          shell: bash
```

## Related environment

Please provide the following information:

Digital Ocean

**Comment by appleboy** [comment]
try

```yaml
        with:
          host: ${{ env.REMOTE_HOST }}
          username: linuxserver.io
          password: password
          port: 2222
          script: |
            #!/usr/bin/env bash
            set -e
            whoami
```
