### ISSUE TITLE
SSH to Tailscale network

### ISSUE THREAD

**Issue by keu** [appleboy/ssh-action#344]
## Describe the bug

Tailscale SSH doesn't need to specify a SSH key/password. But when I leave it empty I got:

```
2024/11/01 21:15:49 Error: can't connect without a private SSH key or password
```

## Yaml Config

Please post your Yaml configuration file along with the output results.

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ec2

    steps:
    - name: Tailscale Auth
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        version: 1.76.1

    - name: Execute deployment script on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC_HOST }}
        username: ${{ secrets.EC_USER }}
        password: ''
        command_timeout: 10m
        script: |
          whoami
```

```
Run appleboy/ssh-action@master
Run echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
Run entrypoint.sh
Will download drone-ssh-1.7.7-linux-amd64 from https://github.com/appleboy/drone-ssh/releases/download/v1.7.7
======= CLI Version =======
Drone SSH version 1.7.7
===========================
[20](/job/32407897636#step:3:21)24/11/01 21:15:49 Error: can't connect without a private SSH key or password
Error: Process completed with exit code 1.
```

## Related environment

Please provide the following information:

1. GH
2. Tailscale 1.76.1
3. -
