### ISSUE TITLE
Upgrading from `1.0.3` to `1.2.0` causes ssh-action to `i/o timeout`

### ISSUE THREAD

**Issue by jcarroll-ls** [appleboy/ssh-action#348]
## Describe the bug

ssh-action was previously working on `1.0.3` but has stopped connecting since upgrading to `1.2.0`.

The error being throw in `1.2.0` as follows:
![image](https://github.com/user-attachments/assets/98fbc528-574f-44bb-9c8f-610c2b817e80)

Screenshot of the successful run using `1.0.3`:
![image](https://github.com/user-attachments/assets/0d3af0d9-4393-4fdc-aa62-93a1452805fe)

## Yaml Config

Please post your Yaml configuration file along with the output results.

```yaml
name: test-ssh-update

on: push

jobs:
  ssh-103:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: ORG-OMITTED/github-actions/openvpn@main
        with:
          config: ${{ secrets.VPN_CONFIG }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}

      - uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_WORKFLOWS_PAT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo hello world 103

  ssh-120:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: ORG-OMITTED/github-actions/openvpn@main
        with:
          config: ${{ secrets.VPN_CONFIG }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}

      - uses: appleboy/ssh-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_WORKFLOWS_PAT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo hello world 120
```

## Related environment

Please provide the following information:

1. Test host ssh service is `OpenSSH 6.6.1`.
