### ISSUE TITLE
Using private SSH keys from github secrets does not work

### ISSUE THREAD

**Issue by adisidev** [appleboy/ssh-action#349]
## Describe the bug

When I copy and paste (or upload through the API) a private key to my GitHub Actions secrets for my repository, it automatically gets formatted as having spaces instead of newlines.  This does not work well with the action, as it always seems to fail the handshake.

## Yaml Config

Here is how I use the action:

```yaml
name: Pull latest gocartio/cartogram-web image on host (go-cart.io)

on:
  # only when triggered manually, after we have tested it ourselves
  workflow_dispatch:
  push:
    branches: [ "main", "create-github-action-to-pull-new-image" ]

jobs:
  pull-new-cartogram-web-image:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy binary to go-cart.io
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_ACCESS_KEY }}
          debug: true
          script: |
           docker-compose -f /home/cartogram/cartogram-docker/docker-compose.yml pull web
           docker-compose -f /home/cartogram/cartogram-docker/docker-compose.yml up -d --no-deps web
```

## Related environment

Please provide the following information:

Changing these spaces to newlines again works (tested using `tmate`). Thus, I do believe the issue lies in the key itself, as I get a libcrypto error trying to use the key in the way it is saved by GitHub secrets.
