### ISSUE TITLE
entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by Ban921** [appleboy/ssh-action#352]
## Describe the bug

When I update from version 1.0.3 to 1.1.0 entrypoint.sh: Permission denied occurs.

## Yaml Config

```yaml
name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.NAME }}
          key:  ${{ secrets.KEY }}
          script: |
            ls
```

## Related environment

Please provide the following information:
My environment is using windows docker and ssh to the GCP host
I tested v1.2.0 and the same situation occurred
![image](https://github.com/user-attachments/assets/4eb7eb1b-e4cf-4170-81a3-b88c3e852c1d)
![image](https://github.com/user-attachments/assets/0d7e1536-7517-42dc-a08d-90dce15ec557)
![image](https://github.com/user-attachments/assets/e8ba1e91-dc2d-4bcd-8bf4-18ffa7d8e4e6)
