### ISSUE TITLE
Multiline script shows failure as success

### ISSUE THREAD

**Issue by Wulfheart** [appleboy/ssh-action#359]
## Describe the bug

When a line in a multiline script fails with a non zero exit code the action still succeeds even though I would expect it to fail.

## Yaml Config

```yaml
name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
         ls ~
         ls /nonexistent <-- This errors but the action still suceeds
         ls ~
```
