### ISSUE TITLE
Same var name in passed envs and in local .env file cause error

### ISSUE THREAD

**Issue by rodshtein** [appleboy/ssh-action#370]
Somehow node can't read right string from a passed env. 

 
## Error
![Image](https://github.com/user-attachments/assets/0a608350-c4d9-4a00-9d6e-ea7cccab6616)

## Local .env file (original string was scrambled)
```env
DATABASE_URL="postgresql://figm:ds_a_dff_s;_ih3123126h_1231@localhost:1234"
```

## Config with issue

```yaml
    steps:
      - name: Update & Restart Server
        uses: appleboy/ssh-action@v1.2.0
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL_PROD}}
        with:
          host: ${{env.HOST}}
          username: ${{env.USER}}
          passphrase: ${{env.SSH_PASS}}
          key: ${{env.SSH_KEY}}
          envs: DATABASE_URL  ❌
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/prod
            nvm install
            npm run prisma:deploy
```

## Config without issue

```yaml
    steps:
      - name: Update & Restart Server
        uses: appleboy/ssh-action@v1.2.0
        env:
          GH_DATABASE_URL: ${{secrets.DATABASE_URL_PROD}}
        with:
          host: ${{env.HOST}}
          username: ${{env.USER}}
          passphrase: ${{env.SSH_PASS}}
          key: ${{env.SSH_KEY}}
          envs: GH_DATABASE_URL  ✅
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/prod
            nvm install
            npm run prisma:deploy
```
