### ISSUE TITLE
why I get an error :"Process exited with status 1"

### ISSUE THREAD

**Issue by samxxxxx** [appleboy/ssh-action#373]
```yml
      - name: Clean target directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }} 
          port: ${{ secrets.ALIYUN_SSH_PORT }} 
          script: |
            Remove-Item -Path "C:\www\app\*" -Recurse -Force
            echo "done !!!!!!!!!!!!!!!!!!!!!!!"
          debug: true
```

======CMD======
Remove-Item -Path "C:\www\app\*" -Recurse -Force
echo "done !!!!!!!!!!!!!!!!!!!!!!!"

======END======
'Remove-Item' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
2025/03/17 01:49:28 Process exited with status 1
���������ļ���
Error: Process completed with exit code 1.

What is the garbled text here, and how can I check the actual error message inside? What needs to be configured?
