### ISSUE TITLE
Multiple commands does not work

### ISSUE THREAD

**Issue by Jamesking56** [appleboy/ssh-action#377]
## Describe the bug

Running multiple commands attempts to run it all as one line, rather than separate commands:

```
cd test cat test.txt
```

Causing this error: `bash: line 1: cd: too many arguments`

## Yaml Config

```yaml
name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              cd test
              cat test.txt
```

## Related environment

Hosting Provider: 20i
Shared hosting, cannot access SSH config information

**Comment by Xavier9896** [comment]
```yml
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }} & tar -xf "dist.zip" -C "${{ secrets.DEPLOY_PATH }}" & robocopy "${{ secrets.DEPLOY_PATH }}/.vitepress/dist" "${{ secrets.DEPLOY_PATH }}" /mov /e & del /f /q "dist.zip" & rd /s /q ".vitepress"
```
Use & to concatenate commands.It works for me.
