### ISSUE TITLE
Building Appleboy docker error

### ISSUE THREAD

**Issue by imyers236** [appleboy/ssh-action#380]
## Describe the bug

When trying to use the scp-action it will not build appleboy

![Image](https://github.com/user-attachments/assets/7fb307ff-a3c5-43c2-83bb-f96abb062300)

## Yaml Config

Please post your Yaml configuration file along with the output results.

```yaml
build:
    runs-on: self-hosted
    timeout-minutes: 2
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Install make
        run: sudo apt-get install make
      - name: Build project
        run: make build
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "tests/a.txt"
```
