### ISSUE TITLE
script_path option does not find the script passed in parameter

### ISSUE THREAD

**Issue by vaevictis** [appleboy/ssh-action#384]
## Describe the bug

I can't get the `script_path` option to work. Using `script`, and passing it one or multiple commands works just fine, so I've validated the connection part to my server. But trying to pass a local, in-repo script file as a parameter to `script_path` keeps returning the same error message, no matter how I attempt multiple relative paths.

## Error stack on Github Actions
```
Run appleboy/ssh-action@v1.2.2
Run echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
Run entrypoint.sh
Will download drone-ssh-1.8.1-linux-amd64 from https://github.com/appleboy/drone-ssh/releases/download/v1.8.1
======= CLI Version =======
Drone SSH version 1.8.1
===========================
2025/04/26 00:50:24 stat scripts/update_vam_and_relaunch_worker.sh: no such file or directory
Error: Process completed with exit code 1.
```

## Yaml Config

Please post your Yaml configuration file along with the output results.

```yaml
name: deploy to prod
env:
  PYTHON_VERSION: "3.11.10"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: <HIDDEN>
          username: <HIDDEN>
          key: ${{ PASSED AS A GITHUB SECRET secrets.(...) }}
          script_path: scripts/update_vam_and_relaunch_worker.sh
```

## Related environment

Please provide the following information:

1. The target is a Digital Ocean server.
2. The version information of your host's SSH service.
```
$ ssh -v localhost
OpenSSH_9.2p1 Debian-2+deb12u5, OpenSSL 3.0.15 3 Sep 2024
```
3. The information from your host's SSH configuration file.
Not sure what's expected here, the whole config file? I doubt it's connection-related, as I can connect just fine with commands passed to the `script` parameter.
