### ISSUE TITLE
Running background command using `&` causes the step to halt and timeout

### ISSUE THREAD

**Issue by asymness** [appleboy/ssh-action#40]
I am executing a command like this in the step:
`python script.py &`
`echo Done`

This causes the step to get stuck in progress after echoing Done and eventually timeout (after ~10 minutes) whereas it should be done in 10 seconds. 
However, if I kill the process (python script.py) manually by SSH'ing to the server, the step completes execution successfully. How can I fix this problem and run background commands successfully?

Other variants I have tried:
`nohup python script.py &`
`disown`

**Comment by asymness** [comment]
Fixed by redirecting all output:
`nohup python script.py > nohup.out 2> nohup.err < /dev/null &`

**Comment by kadukm** [comment]
@asymness thank you! I faced the same problem. Do you know why it works like this? I tried to find an answer to this question for several hours but found nothing.

**Comment by asymness** [comment]
For some reason, the action keeps waiting for stdin, stdout, and stderr. That's why we need to redirect all three outputs to free the terminal. That's all I could gather from this...

**Comment by Saljooq** [comment]
I am running into similar error. I had tried re-directing output and error, but after seeing the suggestions, I added the input too - however my github actions keep running and then timing out and failing:
![image](https://user-images.githubusercontent.com/75107181/234453995-edc68655-2100-4b02-9e68-d88d6fb5a89d.png)

Here's the script:
sudo docker compose --env-file ./.config/.env up  >nohup-log.txt 2>&1  </dev/null &

Any suggestions would be appreciated

**Comment by Saljooq** [comment]
So I've had a very similar issue with docker compose. As per the suggestion I tried redirecting all three fds (input, output and error), but no luck, my github actions keep running and then timing out and failing.

Here's the script:
```bash
nohup sudo docker compose --env-file ./.config/.env up > nohup.out 2> nohup.err < /dev/null &
```

Any help would be appreciated :)

**Comment by mogendi** [comment]
@Saljooq moving `nohup` to a command directly under the list of commands on the action worked for me for some reason.

some something like:
.github/deploy.yaml
```yaml
uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.KEY  }}
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USERNAME  }}
          script: |
            ./some_script
```

./some_script
```bash
nohup ./some_other_script > nohup.out 2> nohup.err < /dev/null &
```

I changed it to:
.github/deploy.yaml
```yaml
uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.KEY  }}
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USERNAME  }}
          script: |
            nohup ./some_script > nohup.out 2> nohup.err < /dev/null &
```
