### ISSUE TITLE
Error: dial tcp PORT: connect: connection refused

### ISSUE THREAD

**Issue by GarryOne** [appleboy/ssh-action#41]
When trying to run a command that is starting a node process, it throws this error
```
Run appleboy/ssh-action@master
  with:
    port: 22
    sync: false
    timeout: 30s
    command_timeout: 10m
    proxy_port: 22
    proxy_timeout: 30s
    script_stop: false
    debug: false
  env:
    USERNAME: ***
    HOST: ***
    KEY: ***
  
    SCRIPT: cd *** && node main.js
    PORT: 3000
/usr/bin/docker run --name e87b522ab8732cb714423cb9b4eda618507167_99b156 --label e87b52 --workdir /github/workspace --rm -e USERNAME -e HOST -e KEY -e SCRIPT -e PORT -e INPUT_HOST -e INPUT_PORT -e INPUT_PASSPHRASE -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_SYNC -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_SCRIPT -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/ests-iot-server/ests-iot-server":"/github/workspace" e87b52:2ab8732cb714423cb9b4eda618507167
======CMD======
cd *** && node main.js

======END======
2020/03/26 23:45:18 dial tcp ***:3000: connect: connection refused

```

**Comment by appleboy** [comment]
@GarryOne You don't need to set the ENV now. just use `with` parameter.

**Comment by devcarlos** [comment]
@appleboy I had a similar issue but in my case I get `connect: connection timed out` but the funny thing is that I can connect from my local MacBook so I think there is a problem on the GitHub Action settings (maybe known_hosts ?)

So this is my result (ignore the ENV settings I'm using that for later):

>   executing remote ssh commands using ssh key32s
> Run appleboy/ssh-action@master
>   with:
>     host: onswivel.com
>     username: ubuntu
>     key: ***
>     timeout: 120s
>     debug: true
>     script: whoami
>   cd on-swivel
>   ls -al
>   
>     port: 22
>     sync: false
>     command_timeout: 10m
>     proxy_port: 22
>     proxy_timeout: 30s
>     script_stop: false
>   env:
>     MONGO_DB_URL: ***
>     ENV: ***
>     PORT: ***
>     JWT_SECRET: ***
>     TWILIO_ACCOUNT_SID: ***
>     TWILIO_AUTH_TOKEN: ***
>     TWILIO_MESSAGE_SERVICE_ID: ***
>     TOKBOX_API_KEY: ***
>     TOKBOX_SECRETE_KEY: ***
>     TEST_USER_PHONE_NUMBER: ***
>     TEST_USER_MAGIC_CODE: ***

I can connect using PEM file like this:

`ssh -i swivel.pem ubuntu@onswivel.com`

So how should I make this work ?

**Comment by EGSatelix** [comment]
I have same issue since 3 months.
Same script works fine before.

**Comment by appleboy** [comment]
@EGSatelix Post your YAML and don't use the `env` in settings.

**Comment by EGSatelix** [comment]
```
name: Deployer en prod

on:
  push:
    branches:    
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Executer script sur serveur Admin via (avec clé)
      uses: appleboy/ssh-action@v0.0.8
      with:
        port: 22
        username: ******
        host: *************.eu-west-3.compute.amazonaws.com
        key_path: '.aws/my_key'
        script: |
          sh /home/myuser/deploy/start.sh

```

**dial tcp *******:5432: connect: connection refused**

I have this error and i don't understand why port is 5432
