### ISSUE TITLE
End Successfully even if  the git command error occurs

### ISSUE THREAD

**Issue by mii226** [appleboy/ssh-action#48]
Hello.
The ssh server is WindowsServer2016.
yaml is here.

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST}}
        username: ${{ secrets.USER }}
        port: ${{ secrets.SSH_PORT}}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        script: |
          cd ${{ secrets.DEPLOY_PATH }}&git pull origin master&iisreset /restart
```

Windows command doesn't seem to work if multiple lines are specified, so I wrote script command like this.

The log is below.
```
======CMD======
cd ***&git pull origin master&iisreset /restart

======END======

~~~~~~~~~~~~~~~
err: * branch master -> FETCH_HEAD
err: 3573750..76179a8 master -> origin/master
err: error: Your local changes to the following files would be overwritten by merge: ★here
err: config/settings.py
err: requirements.txt
err: Please commit your changes or stash them before you merge.
err: Aborting
out: Updating b032eb0..76179a8
out:
out: Attempting stop...
out: Internet services successfully stopped
out: Attempting start...
out: Internet services successfully restarted
==============================================
✅ Successfully executed commands to all host.
==============================================
```
I don't know if this behavior is normal or a bug.
Please advise if my configuration is wrong.

**Comment by appleboy** [comment]
@mii226 Can you help to try the following config:

```
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          git pull origin master
          iisreset /restart
```

**Comment by mii226** [comment]
Thank you for your replying message.

If you write the config as you say,
"cd" on the first line is executed, but the commands on the second and third lines seem to be terminated without being executed. (If the command is executed, it will be output to the log, right?)


This log is the following.
```
======CMD======
cd ***
git pull origin master
iisreset /restart

======END======
==============================================
✅ Successfully executed commands to all host.
==============================================
```

**Comment by appleboy** [comment]
> (If the command is executed, it will be output to the log, right?)

Yes. Can you also add more debug command in your config like `echo`?

**Comment by mii226** [comment]
@appleboy 
> Can you also add more debug command in your config like echo?

OK.
```
======CMD======
echo AAAAA
echo BBBBB
echo CCCCC
======END======
out: AAAAA
==============================================
✅ Successfully executed commands to all host.
==============================================
```

**Comment by appleboy** [comment]
I can't reproduce the issue. You can see my example:

https://github.com/appleboy/ssh-action/blob/ad6643f7053e0afbd2701670df746f69255670bf/.github/workflows/ci.yml#L30-L39

and the screenshot: https://github.com/appleboy/ssh-action/runs/632414557

<img width="479" alt="Screen Shot 2020-04-30 at 4 00 56 PM" src="https://user-images.githubusercontent.com/21979/80686764-d26cee00-8afb-11ea-8afb-477bb4cccaf9.png">

**Comment by mii226** [comment]
> I can't reproduce the issue. 

I am running the script against the windows environment.
I don't know if the work will change depending on the environment...

**Comment by ghunti** [comment]
I have the same issue, it seems that when using multiple commands, if the last one succeeds, the process caries on.
This is my script
```
with:
        host: <REDACTED>
        username: <REDACTED>
        passphrase: <REDACTED>
        key: <REDACTED>
        script: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "<REDACTED>"
          cd XXXXX
          git pull
          composer install --optimize-autoloader --no-dev
          php artisan config:cache
          php artisan view:cache
          php artisan migrate --force
```

And this is the output:
![Screenshot from 2020-07-10 22-40-43](https://user-images.githubusercontent.com/392038/87205426-5531d680-c2ff-11ea-95b6-7abb2ddeac12.png)

**Comment by tgouala** [comment]
I think this is the responsibility of the shell script to return an error when one of the commands fails. `set -e` on top of your bash script will exit the execution with an error code if any of the command fails. SHH action will fails and the github workflow will indicate the build failed.

**Comment by appleboy** [comment]
@ghunti @tgouala Try to add `script_stop: true`.

**Comment by MurylloEx** [comment]
> Acho que é responsabilidade do shell script retornar um erro quando um dos comandos falha. `set -e`no topo do seu script bash sairá da execução com um código de erro se algum comando falhar. A ação SHH falhará e o fluxo de trabalho do github indicará que a compilação falhou.

Thanks, after 2 years this worked for me as well!

**Comment by dule-kitemetric** [comment]
> [@ghunti](https://github.com/ghunti) [@tgouala](https://github.com/tgouala) Try to add `script_stop: true`.

**NOTE Feb 18, 2025**: My message is same to the [above comment](https://github.com/appleboy/ssh-action/issues/48#issuecomment-1247465613). But I post here for the up-to-date status
- `script_stop` is no longer supported from Dec 2, 2024.
  - See https://github.com/appleboy/ssh-action/pull/350
- Current solution to return an error when one of the commands fails: Place `set -e` at the top of the script.
  - See https://github.com/appleboy/ssh-action/issues/335#issuecomment-2519580776
  - Example
```
      - id: stdout01
        name: ssh command with stdout 01
        uses: appleboy/ssh-action@master
        with:
          script: |
            #!/usr/bin/env bash
            set -e
            
           # ... remaining commands
```
