### ISSUE TITLE
Using secrets within commands

### ISSUE THREAD

**Issue by sgurlt** [appleboy/ssh-action#52]
Hey,

is it possible to use secrets within the commands? Like for example:

```
      - name: I123
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.1 }}
          username: ${{ secrets.2 }}
          key: ${{ secrets.3 }}
          proxy_host: ${{ secrets.4 }}
          proxy_username: ${{ secrets.5 }}
          proxy_key: ${{ secrets.6 }}
          script: |
            echo ${{ secrets.7 }}
```

Best regards
Sebastian
