### ISSUE TITLE
I/O Timeout Error

### ISSUE THREAD

**Issue by emiryumak** [appleboy/ssh-action#53]
It doesn't just make any other error:

`======CMD======
docker rm -f $(docker ps -aq -f name=erp-front)
docker rmi $(docker images | grep 'emiryumak/erp-front' | awk '{print $3}')
docker pull emiryumak/erp-front:latest
docker run --name erp-front -p 5000:80 --restart=always -d emiryumak/erp-front

======END======
======ENV======

======END======
2020/05/16 20:31:15 dial tcp ***:***: i/o timeout`

I don't understand thats error. Its meaning can not connect to my server?

**Comment by efontan** [comment]
I had the same problem and solved it adding this `timeout` variable to the step config:
```      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        port: ${{ secrets.DO_PORT }}
        timeout: 120s
```

**Comment by appleboy** [comment]
Please post your config and help to try the latest version?

**Comment by emiryumak** [comment]
> Please post your config and help to try the latest version?

Hi thank you for your reply

_my workflow file;_
`name: KantERP APP Container
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kantist/erp-app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        snapshot: true
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.KANT_SSH_HOST }}
        username: ${{ secrets.KANT_SSH_USERNAME }}
        password: ${{ secrets.KANT_SSH_PASSWORD }}
        port: ${{ secrets.KANT_SSH_PORT }}
        debug: true
        script: |
          docker rm -f erp-app
          docker rmi kantist/erp-app
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker pull kantist/erp-app:latest
          docker run --name erp-app -p 9101:80 --restart=always -d kantist/erp-app`

its return 
`/usr/bin/docker run --name d33c8fb8f67113483d82f46f8df194eda4_5f5a1e --label 3888d3 --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_PORT -e INPUT_DEBUG -e INPUT_SCRIPT -e INPUT_PASSPHRASE -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/erp-app/erp-app":"/github/workspace" 3888d3:3c8fb8f67113483d82f46f8df194eda4
======CMD======
docker rm -f erp-app
docker rmi ***/erp-app
docker login --username *** --password ***
docker pull ***/erp-app:latest
docker run --name erp-app -p 9101:80 --restart=always -d ***/erp-app

======END======
======ENV======

======END======
2020/06/18 10:06:57 dial tcp ***:***: i/o timeout`


**I tried to upgrade the timeout not working thats.**

**Comment by appleboy** [comment]
Can you make sure that you can ssh to the remote server using the following config?

```yaml
host: ${{ secrets.KANT_SSH_HOST }}
username: ${{ secrets.KANT_SSH_USERNAME }}
password: ${{ secrets.KANT_SSH_PASSWORD }}
port: ${{ secrets.KANT_SSH_PORT }}
```

**Comment by emiryumak** [comment]
> Can you make sure that you can ssh to the remote server using the following config?
> 
> 
> 
> ```yaml
> 
> host: ${{ secrets.KANT_SSH_HOST }}
> 
> username: ${{ secrets.KANT_SSH_USERNAME }}
> 
> password: ${{ secrets.KANT_SSH_PASSWORD }}
> 
> port: ${{ secrets.KANT_SSH_PORT }}
> 
> ```

It’s working on my macbook air terminal

**Comment by appleboy** [comment]
@emiryumak I will add some debug information in the plugin.

**Comment by emiryumak** [comment]
Hi @appleboy i test this for @master branch your plugin. I can not see another debug information. Thats all log;
```======CMD======
docker rm -f erp-app
docker rmi ***/erp-app
docker login --username *** --password ***
docker pull ***/erp-app:latest
docker run --name erp-app -p 9101:80 --restart=always -d ***/erp-app

======END======
======ENV======

======END======
2020/06/27 11:20:50 dial tcp ***:***: connect: connection timed out

**Comment by hopewise** [comment]
I am having the same issue, although it has to work before.. I can ssh using my mac with the same private key, user and port

**Comment by chaudharykiran** [comment]
I am same issue as well.

**Comment by appleboy** [comment]
duplicated of https://github.com/appleboy/ssh-action/issues/32

**Comment by brerdem** [comment]
I'm getting the same error. Trying to connect to a Windows Server 2008 r2 with freesshd on it.

**Comment by gokdeemir** [comment]
I have this same error, Although I checked my  secrets three times.

**Comment by paul-uz** [comment]
Same error here, using fully valid SSH credentials (username, host + secret key)

**Comment by zhuhanming** [comment]
I faced the same issue as well (while having none with `appleboy/scp-action`) and was eventually able to resolve this by reconfiguring  `ufw` on my server. The action for `22/tcp` was `LIMIT` for some reason.

Running
```bash
sudo ufw allow ssh
```
fixed it for me.

**Comment by Shaance** [comment]
> I faced the same issue as well (while having none with `appleboy/scp-action`) and was eventually able to resolve this by reconfiguring `ufw` on my server. The action for `22/tcp` was `LIMIT` for some reason.
> 
> Running
> 
> ```shell
> sudo ufw allow ssh
> ```
> 
> fixed it for me.

Using GCP where I have ssh allowed on instance firewall and executed  `sudo ufw allow ssh`, checked it was enabled with `sudo ufw status` and it is. Still facing timeout issue.

**Comment by danieeis** [comment]
I had the same issue, occurs sometimes, no always. But is frustacting. I check my secrets and is correct, the ufw allow ssh is set. So.. is an issue intermittent. When re run all jobs fix the problem, but sometimes no.

**Comment by Kalaschnik** [comment]
Same here :/ Is there any news on this?

**Comment by AsrinDayananda288Group** [comment]
This fixed my issue,
Add IP addresses of "actions" from https://api.github.com/meta to server your ssh'ing into.
Github server ips change so if starts failing again they need to change

**Comment by luisfalconmx** [comment]
## The Problem
After several hours trying to solve this problem, I came to the next conclusion:

Apparently there are some commands like `docker rm -f $(docker ps -aq -f name=erp-front)` or `docker rmi $(docker images | grep 'emiryumak/erp-front' | awk '{print $3}')` that make the connection saturate and throw the I/O Timeout error.

This may be because the command `docker rmi $(docker images | grep 'emiryumak/erp-front' | awk '{print $3}')` first tries to return all images named `emiryumak/erp-front` and then remove each of them, which can be too complicated to process.

## Possible Solution
My recommendation would be to keep the commands as simple as possible or use them as shown in official documentation. Also make sure you configure the credentials correctly. In case you use an ssh key make sure to add the public key on the server and the private key in the repository as a secret.

[Setting up a SSH Key](https://github.com/marketplace/actions/ssh-remote-commands#setting-up-a-ssh-key)

Some examples of how to use the commands correctly.

### Delete a specific container
``` bash
# ❌ do not this
docker rm -f $(docker ps -aq -f name=erp-front)
```

``` bash
# ✅ do this
docker rm my_super_app -f

# or this
docker run --name my_super_app -d --rm -p 80:80 octocat/myimage:latest
docker stop my_super_app
```
### Delete old and unused images

``` bash
# ❌ do not this
docker rmi $(docker images | grep 'emiryumak/erp-front' | awk '{print $3}')
```

``` bash
# ✅ do this
docker image prune -a -f
```

## Workflow File
This is the configuration that I am using to run a docker container on a server via ssh every time I publish a new release

``` yaml
name: CD
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker system prune -a -f
            docker stop my_super_app
            docker run --name my_super_app -d --rm -p 80:80 octocat/myimage:latest
```

### With environment variables
``` yaml
name: CD
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get repository metadata
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker system prune -a -f
            docker stop ${{ env.REPOSITORY_OWNER }}_${{ env.REPOSITORY_SLUG }}
            docker run --name ${{ env.REPOSITORY_OWNER }}_${{ env.REPOSITORY_SLUG }} -d --rm -p ${{ secrets.APP_PORT }} ${{ env.REPOSITORY_FULL_NAME }}:latest
```
---

I hope this information has been useful to you 😉
