### ISSUE TITLE
Legacy algorithm support

### ISSUE THREAD

**Issue by abdelhamid-attaby** [appleboy/ssh-action#56]
I got the following message when trying to ssh a BlueHost server:

```
2020/05/23 13:43:07 ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group-exchange-sha256]
```

Even when I try `ssh-action@v0.0.9`.

**Comment by appleboy** [comment]
related to issue https://github.com/appleboy/scp-action/issues/15

@abdelhamid-attaby Can you provide detailed steps about how to generate the ssh key?

**Comment by appleboy** [comment]
Add the algorithm to your client config:

1. open `/etc/ssh/ssh_config`
2. update `KexAlgorithms` setting and add `diffie-hellman-group-exchange-sha256`

**Comment by abdelhamid-attaby** [comment]
@appleboy I generated the key using the `Manage SSH Keys` in `cPanel`.

**Comment by abdelhamid-attaby** [comment]
> Add the algorithm to your client config:
> 
> 1. open `/etc/ssh/ssh_config`
> 2. update `KexAlgorithms` setting and add `diffie-hellman-group-exchange-sha256`

I am afraid I cannot do that because it is shared hosting.

**Comment by appleboy** [comment]
@abdelhamid-attaby Can you login to your server via ssh?

**Comment by abdelhamid-attaby** [comment]
@appleboy Yes I can using a downloaded private key.

**Comment by abdelhamid-attaby** [comment]
@appleboy any idea? The KexAlgorithm should be added to the compiled ubuntu image of the `ssh-action`.

**Comment by appleboy** [comment]
@abdelhamid-attaby I will take it.

**Comment by abdelhamid-attaby** [comment]
@appleboy Thanks

**Comment by appleboy** [comment]
@abdelhamid-attaby Please help to try https://github.com/appleboy/ssh-action/releases/tag/v0.1.0 version and give me feedback.

**Comment by abdelhamid-attaby** [comment]
@appleboy same here 🙁

**Comment by appleboy** [comment]
@abdelhamid-attaby Please add the following:

```yaml
use_insecure_cipher: true
```

**Comment by abdelhamid-attaby** [comment]
> @abdelhamid-attaby Please add the following:
> 
> 
> 
> ```yaml
> 
> use_insecure_cipher: true
> 
> ```
> 
> 
> 
> see https://github.com/appleboy/ssh-action#input-variables

@appleboy same 

```

2020/05/24 03:06:24 ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group-exchange-sha256]

```

**Comment by appleboy** [comment]
@abdelhamid-attaby Please help to try the master version

```
uses: appleboy/ssh-action@master
```

**Comment by abdelhamid-attaby** [comment]
@appleboy same

**Comment by appleboy** [comment]
@abdelhamid-attaby Can you post your config?

**Comment by abdelhamid-attaby** [comment]
> @abdelhamid-attaby Can you post your config?

```

name: Deploy to Prod
on:
  push:
    branches: 
      - master
jobs:
  Deploy-To-Dev:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: coligotech.com
        username: coligote
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        use_insecure_cipher: true

        script: |
          cd public_html/almoultka
          git checkout master
          git pull

```
