### ISSUE TITLE
Environment variables don't work

### ISSUE THREAD

**Issue by dmitryrn** [appleboy/ssh-action#58]
My actions config:
```bash
name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        PG_DATA_VOLUME: ${{ secrets.PG_DATA_VOLUME }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        PG_USERNAME: ${{ secrets.PG_USERNAME }}
        PG_DBNAME: ${{ secrets.PG_DBNAME }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: PG_DATA_VOLUME,PG_PASSWORD,PG_USERNAME,PG_DBNAME
        script: |
          env
```

`env` command outputs env vars, but it doesn't output PG_DATA_VOLUME, PG_PASSWORD, etc.
So the issue is env vars are not available in ssh session.

**Comment by dmitryrn** [comment]
Output from container:

/usr/bin/docker run --name be76db878b5b436904458999e6e114abfdf89c_2cac6c --label be76db --workdir /github/workspace --rm -e PG_DATA_VOLUME -e PG_PASSWORD -e PG_USERNAME -e PG_DBNAME -e INPUT_HOST -e INPUT_USERNAME -e INPUT_KEY -e INPUT_PORT -e INPUT_ENVS -e INPUT_SCRIPT -e INPUT_PASSPHRASE -e INPUT_PASSWORD -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/patreon-***/patreon-***":"/github/workspace" be76db:878b5b436904458999e6e114abfdf89c

**Comment by dngconsulting** [comment]
Same problem here, the files created with remote commands are owned by user 1001:docker. And sudo -E don't use env variables .. It there any way to change the target user (on the remote host) ? Thanks

**Comment by appleboy** [comment]
It is working for me:

https://github.com/appleboy/ssh-action/blob/682eb0ddda5d4b97a4b9b7ae1314c2f75254f9d9/.github/workflows/ci.yml#L67-L82

**Comment by dngconsulting** [comment]
This doesn't work for me. 
Had to do that, which is pretty uggly :

`name: Run remote server
       uses: appleboy/ssh-action@master
       env:
          POSTGRES_HOST: ${{ secrets.PROD_POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.PROD_POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.PROD_POSTGRES_PORT}}
          POSTGRES_USER: ${{ secrets.PROD_POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.PROD_POSTGRES_DB }}
       with:
         host: ${{ secrets.PROD_HOST }}
         username: ${{ secrets.PROD_LOGIN }}
         key: ${{ secrets.PROD_SSH_KEY  }}
         port: 22
         script: |     
              export POSTGRES_HOST=${{ secrets.PROD_POSTGRES_HOST }}
              export POSTGRES_PASSWORD=${{ secrets.PROD_POSTGRES_PASSWORD }}
              export POSTGRES_PORT=${{ secrets.PROD_POSTGRES_PORT}}
              export POSTGRES_USER=${{ secrets.PROD_POSTGRES_USER }}
              export POSTGRES_DB=${{ secrets.PROD_POSTGRES_DB }}
              myscript.sh (that needs previous ENV Variables)

`

**Comment by appleboy** [comment]
@dngconsulting change the script:

```
         script: |     
              export POSTGRES_HOST=$POSTGRES_HOST
              export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
              export POSTGRES_PORT=$POSTGRES_PORT
              export POSTGRES_USER=$POSTGRES_USER
              export POSTGRES_DB=$POSTGRES_DB
              myscript.sh (that needs previous ENV Variables)
```

and add missing property:

```
with:
  envs: POSTGRES_HOST,POSTGRES_PASSWORD,POSTGRES_PORT,POSTGRES_USER,POSTGRES_DB
```

**Comment by appleboy** [comment]
I will close the issue. Please feel free to reopen if facing the same problem.

**Comment by espoirMur** [comment]
having the same issue here, is this mandatory to make it work? `SHA: ${{ github.sha }}`

**Comment by phigrey** [comment]
It doesn't work for me.
```
   - name: Run a multi-line script
      uses: appleboy/ssh-action@master
      env:
        DB_HOST: ${{ secrets.HOTFIX_DICT_DB_HOST }}
        TEST_HOST: "127.0.0.1"
      with:
        host: ${{ secrets.HOTFIX_HOST }}
        username: ${{ secrets.HOTFIX_USERNAME }}
        password: ${{ secrets.HOTFIX_PASSWORD }}
        port: 22
        envs: DB_HOST, TEST_HOST
        script: |
          export DB_HOST=$DB_HOST
          export TEST_HOST=$TEST_HOST
```
When I logged into the remote server, `echo $DB_HOST` or `echo $TEST_HOST`, it was just blank.

**Comment by angelorc** [comment]
Still having an issue, this is my actions

```
  deploy-api:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Droplets already have docker, doctl + auth, and curl installed
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: "3001"
          NODE_ENV: "production"
        with:
          host: ${{ secrets.DO_API_HOST }}
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          envs: MONGO_URI,PORT,NODE_ENV
          script: |
            export MONGO_URI=$MONGO_URI
            export PORT=$PORT
            export NODE_ENV=$NODE_ENV

            doctl registry login --expiry-seconds 180
            docker pull registry.digitalocean.com/registry/api:latest

            docker stop api || true
            docker rm api || true

            echo "starting server instance..."
            docker run -d \
              --restart always \
              -p 0.0.0.0:80:80 \
              --name api \
              registry.digitalocean.com/registry/api:latest
```

and this is the docker log

```
We are live on undefined mode on port undefined
For some reasons we couldn't connect to the DB MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
```

**Comment by zakst** [comment]
Same here still got the same issue

```yaml
    - name: Restart my-app
      uses: appleboy/ssh-action@master
      env:
        MY_ENV_VAR: ${{ secrets.API_SECRET }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        envs: MY_ENV_VAR
        script: |
          export MY_ENV_VAR=$MY_ENV_VAR
          pm2 stop my-app
          pm2 start /var/www/html/dist/apps/my-app/main.js --watch --name my-app

```
i also tried 

the app stops and starts successfully but can not read the env `MY_ENV_VAR`
