### ISSUE TITLE
Always returns ssh: handshake failed connecting to EC2

### ISSUE THREAD

**Issue by samfrm** [appleboy/ssh-action#64]
I cannot make it work with EC2.

my config:
```
jobs:
  Deploy-To-Dev:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH Keys and known_hosts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script: whoami
```

Output: 
`ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

I tried this action https://github.com/shimataro/ssh-key-action and worked which needs `known_hosts`.

How can I pass `known_hosts` or where I did wrong?
