### ISSUE TITLE
SSH key works from my local machine, but not with this Action.

### ISSUE THREAD

**Issue by greaveselliott** [appleboy/ssh-action#7]
Hi, I am having some trouble getting your action to connect to my DigitialOcean droplet.
I have tried both SSH connections via a SSH Key and a standard User/Password.

**The error**
``` handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain```

**My config**
```yml
- name: Deploy
    uses: appleboy/ssh-action@master
    with:
       host: ${{ secrets.DIGITAL_OCEAN_DROPLET_HOST }}
       username: ${{ secrets.DIGITAL_OCEAN_DROPLET_USER }}
       password: ${{ secrets.DIGITAL_OCEAN_DROPLET_PASSWORD }}
       script: whoami
```

Lastly, reviewing some of the resolved repo issues, I followed your advice to follow this article http://www.linuxproblem.org/art_9.html which gets you to append the public SSH key to the remote servers `authorized_keys` file. 

Cheers,

**Comment by appleboy** [comment]
https://github.com/appleboy/ssh-action/blob/aa1ecdd19aeebf7f9515f55b4801b027b55d40ac/.github/workflows/ci.yml#L9-L25

It is working for me using password or ssh keys.

You can try the ssh command first that makes sure you can connect to a server via CLI.

**Comment by greaveselliott** [comment]
Thanks for the response @appleboy. It was an issue with my credentials. I've fixed this now.

Although I am now having `docker command not found` CLI once I SSH into my box? When I SSH from terminal, this works fine, any idea?

**Comment by sgurlt** [comment]
> Thanks for the response @appleboy. It was an issue with my credentials. I've fixed this now.

I am actually facing the same issue, how did you fix it in the end?

**Comment by yonatan-gelbard** [comment]
@sgurlt Its probably wrong username. If it works for you locally make sure you set the same username (i.e. of you use locally ssh git@host, so username should be "git")

**Comment by sgurlt** [comment]
Thanks for commenting back, for me it was an issue with the ssh key, I also have resolved it in the meantime.

**Comment by maxarouca** [comment]
> https://github.com/appleboy/ssh-action/blob/aa1ecdd19aeebf7f9515f55b4801b027b55d40ac/.github/workflows/ci.yml#L9-L25
> 
> It is working for me using password or ssh keys.
> 
> You can try the ssh command first that makes sure you can connect to a server via CLI.

Will I use the same ssh key configured on my server?

**Comment by ezeikel** [comment]
Having a similar issue with my Digital Ocean droplet and it's driving me crazy. I can connect from my Mac terminal fine using `username@droplet-ip-address` but when I do it via Github Actions I get the handshake failed error.

I pasted the contents of the private key on my droplet into the secret for `PRIVATE_KEY` and the `HOST` is the ip address.

Not sure where this is falling over. My private key starts with:
`-----BEGIN RSA PRIVATE KEY-----`

I've seen some examples with `BEGIN OPEN SSH PRIVATE KEY`

Maybe that could be the issue?

**Comment by ezeikel** [comment]
> Hi, I am having some trouble getting your action to connect to my DigitialOcean droplet.
> I have tried both SSH connections via a SSH Key and a standard User/Password.
> 
> **The error**
> ` handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`
> 
> **My config**
> 
> ```yaml
> - name: Deploy
>     uses: appleboy/ssh-action@master
>     with:
>        host: ${{ secrets.DIGITAL_OCEAN_DROPLET_HOST }}
>        username: ${{ secrets.DIGITAL_OCEAN_DROPLET_USER }}
>        password: ${{ secrets.DIGITAL_OCEAN_DROPLET_PASSWORD }}
>        script: whoami
> ```
> 
> Lastly, reviewing some of the resolved repo issues, I followed your advice to follow this article http://www.linuxproblem.org/art_9.html which gets you to append the public SSH key to the remote servers `authorized_keys` file.
> 
> Cheers,

I also looked at this post but wondering how we would add a public key from Github to the `authorized_keys` file on my Digital Ocean droplet?

**Comment by vrusua** [comment]
> I also looked at this post but wondering how we would add a public key from Github to the `authorized_keys` file on my Digital Ocean droplet?

Hi @ezeikel,

it looks like you should do this once manually through your terminal or in DO console, depending on your security settings.

Cheers

**Comment by camleng** [comment]
I think I'm just missing something, but which public key do I use? I have a public key for my server, but I have not been able to get it to work with using the output of `ssh-keyscan github.com`.

**Comment by GTHell** [comment]
To those who had ssh problem with this github action + digital ocean, don't use SSH option when create droplet. Use password generated one!

**Comment by parrasajad** [comment]
Hi @ezeikel , @camleng ,

you should store the public key from key pair generated using `ssh-keygen` into `authorized_keys`

**Comment by cglusky** [comment]
I ended up disabling ufw on the droplet and using the DO Cloud firewall.  I used the automation script on initial droplet creation that runs this at the end:

```
# Add exception for SSH and then enable UFW firewall
ufw allow OpenSSH
```

I assumed that would open port 22 to all tcp traffic but perhaps it does not?

If you prefer ufw you might try opening port 22 to tcp rather than use "allow OpenSSH"

**Comment by alorwu** [comment]
@appleboy Which private key do I put on Github? Is it the private key on my local mac or the private key of my digital ocean server?

**Comment by appleboy** [comment]
@appleboy Your private key on your mac. Please show your ssh command.

**Comment by henrylemmon** [comment]
@appleboy 
I have been trying for a week I must be missing something. Here is my error in github:

2020/12/28 05:30:44 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain.

Here is the script:

```
deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |

            cd /var/www/

            git checkout -f

            git pull origin master
```
