### ISSUE TITLE
npm command not found and unable to look up myuser@github.com

### ISSUE THREAD

**Issue by rahulserver** [appleboy/ssh-action#70]
Here is my main.yml
```
name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Node Js
      uses: actions/setup-node@v1
       
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master        
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          service myservice stop
          cd leancrm-backend
          git pull git://myuser@github.com/mycmp/myapp-backend.git master
          npm install
          service myservice start

```

It gives this error: 
```
======CMD======
service myservice stop
cd myapp-backend
git pull git://myuser@github.com/mycmp/myapp-backend.git master
npm install
service myservice start

======END======
err: fatal: Unable to look up myuser@github.com (port 9418) (Name or service not known)
err: bash: line 3: npm: command not found
==============================================
```

So its not connecting to git and also not able to find npm. I am sure that these exist on the server as I use them regularly. 
How do I make this work?
Related SO post: https://stackoverflow.com/questions/62863080/github-actions-err-bash-line-3-npm-command-not-found
