### ISSUE TITLE
Dynamic hosts

### ISSUE THREAD

**Issue by anddimario** [appleboy/ssh-action#72]
Is there a correct way to get dynamic hosts list from an url and use them as host?

**Comment by anddimario** [comment]
Founded a solution:
```
    - name: Get hosts
      id: get_hosts
      run: | 
        hosts=`...`
        echo "::set-output name=HOSTS::$hosts"
    - name: SSH
      uses: appleboy/ssh-action@master
      with:
        USERNAME: ...
        HOST: ${{ steps.get_hosts.outputs.HOSTS }}
        KEY: ${{ secrets.KEY }}
        SCRIPT: |
          ...
```
