### ISSUE TITLE
error on docker command not found in ssh_remote scripts

### ISSUE THREAD

**Issue by pasudo123** [appleboy/ssh-action#73]
hello.

please contact the remote server using ssh-action, so docker command cannot be executed.
currently i have sent a file to a remote server using github action (appleboy/scp_action).

and a docker installed on the remote server.
but when i try to run docker command in `script` _input variable_

`err: docker command not found` appears.

could you get some information about this?

Below is my github action yml file.
```yml
docker_compose_run_job:
    needs: backend_build_and_scp
    name: docker-compose run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: execute remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          script_stop: true
          script: |
            whoami
            pwd
            cd /volume1/docker/deploy/www/contact-movie-web/installation
            pwd
            docker -v // error !!
```
