### ISSUE TITLE
Multiline SSH commands interpreted as single lines

### ISSUE THREAD

**Issue by adamkdean** [appleboy/ssh-action#75]
There may be a simple solution to this but so far I've been unable to find it.

The follow script has three commands: `docker stop`, `docker rm`, and `docker run`. Unfortunately, the backslash `\` at the end of `docker run` is ignored, and so each of the params that follow are interpreted as their own commands.

```
script: |
  docker stop example
  docker rm example
  docker run \
    --detach \
    --restart always \
    --publish 80:80 \
    --publish 443:443 \
    --name example \
    --network example-network \
    --volume example-volume:/var/example/volume \
    example/image-name
```

While all of this could fit on one line, it'll make more complex workflows unreadable and harder to maintain.

**Comment by KerberosMorphy** [comment]
`script` is a variable, whatever you pass will be interpreted by the runner before being run.

Example:

```yaml
script: |
  echo $(ls) # Will echo the Runner directory and probable raise an error somewhere
  echo \$(ls) # Will echo the remote directory
```

If you want multiline command you should escaping the `\` so `\\` (Tested and work):

```yaml
script: |
  ls \\
    --lah
```

**Comment by adamkdean** [comment]
Ah! Of everything I tried, I never thought to escape the backslash. I'll give that a go. Thanks @KerberosMorphy!

**Comment by adamkdean** [comment]
Interestingly, @KerberosMorphy, I've just tried the multiline ls command and it's not worked. 

```
======CMD======
ls \\
  -al

======END======
err: ls: cannot access '\': No such file or directory
2020/08/03 10:30:54 Process exited with status 2
```

This is using `appleboy/ssh-action@master`, so maybe I need to test with one of the releases. Which version did you use? Thanks in advance

**Comment by adamkdean** [comment]
I've tried blank lines, `\`, `\\`, `\n`, and `\\n` without any luck. This is definitely something which will require some work with drone-ssh I'm afraid @appleboy.

**Comment by KerberosMorphy** [comment]
Sorry, my bad, I had adapted this action to work with Bitbucket/GitLab/GitHub. When talking to you I was testing on bitbucket and it's works there.

For GitHub I use directly:
```yml
jobs:
  ssh_job:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            ls \
              -lah
```

And it's working.

```sh
======CMD======
ls \
  -lah

======END======
out: total 36K
out: drwxr-xr-x  5 user user 4.0K Apr 14 18:58 .
out: drwxr-xr-x 31 root       root       4.0K Jul 28 15:18 ..
out: -rw-r--r--  1 user user  220 Aug 31  2015 .bash_logout
out: -rw-r--r--  1 user user 3.7K Aug 31  2015 .bashrc
out: drwx------  3 user user 4.0K Apr 14 19:09 .cache
out: -rw-r--r--  1 user user 655 Jun 24  2016 .profile
out: drwx------  2 user user 4.0K Apr 14 13:23 .ssh
out: drwxrwxr-x  5 user user 4.0K Apr 14 18:58 .vscode-server
out: -rw-rw-r--  1 user user 185 Apr 14 18:59 .wget-hsts
==============================================
✅ Successfully executed commands to all host.
==============================================
```
