### ISSUE TITLE
environment variable not working

### ISSUE THREAD

**Issue by dimzeta** [appleboy/ssh-action#79]
I try to use environment variables to deploy my app, but they seem to not working. I tried different things, unsuccessfully.

```
    deploy:
        name: Deploy
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              env:
                DEPLOY_SCRIPT_PATH: ${{ secrets.DEPLOY_SCRIPT_PATH }}
                BRANCH_NAME: ${BRANCH_NAME}
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                port: ${{ secrets.SSH_PORT }}
                envs: DEPLOY_SCRIPT_PATH,BRANCH_NAME
                script_stop: true
                script: $DEPLOY_SCRIPT_PATH $BRANCH_NAME
```

Output:

```
======CMD======
$DEPLOY_SCRIPT_PATH $BRANCH_NAME
======END======
out: ----- Branch: ${BRANCH_NAME}. -----
out: ----- Environment: ${BRANCH_NAME}. -----
...
```
