### ISSUE TITLE
Deployment to multiple hosts with different ports

### ISSUE THREAD

**Issue by saippuakauppias** [appleboy/ssh-action#85]
We send the same release to several servers, but for security we use different ports.
Unfortunately, the current implementation does not provide an option to specify a port in the host field - github action falls with an error: `dial tcp: lookup some.hostname.com:6123: no such host`

Could you please add such functionality so that we do not duplicate the same code to send the release several times (4 times in our case)?

It would be great if it worked like this:
```
  - name: multiple host
    uses: appleboy/ssh-action@master
    with:
     host: "foo.com:1234,bar.com,baz:4321"
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
      script: |
        whoami
        ls -al
```

Let the default port be specified as port 22 or the one that stands in the "port" field, but if the host has its own, you should use it.

Thank you very much!

**Comment by appleboy** [comment]
Try to set up multiple sections like as below:

```
  - name: A host
    uses: appleboy/ssh-action@master
    with:
     host: "foo.com"
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: 1234
      script: |
        whoami
        ls -al
  - name: B host
    uses: appleboy/ssh-action@master
    with:
     host: "bar.com"
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: 22
      script: |
        whoami
        ls -al
```

run parallel
