### ISSUE TITLE
Environment env cannot be used in remote server

### ISSUE THREAD

**Issue by phigrey** [appleboy/ssh-action#86]
I have checked #58, and it seems to be the same problem I have accounted, somehow it doesn't work. 

```
   - name: Run a multi-line script
      uses: appleboy/ssh-action@master
      env:
        DB_HOST: ${{ secrets.HOTFIX_DICT_DB_HOST }}
        TEST_HOST: "127.0.0.1"
      with:
        host: ${{ secrets.HOTFIX_HOST }}
        username: ${{ secrets.HOTFIX_USERNAME }}
        password: ${{ secrets.HOTFIX_PASSWORD }}
        port: 22
        envs: DB_HOST, TEST_HOST
        script: |
          export DB_HOST=$DB_HOST
          export TEST_HOST=$TEST_HOST
```
