### ISSUE TITLE
problem with PORT env

### ISSUE THREAD

**Issue by vladislav-sevostyanov** [appleboy/ssh-action#89]
My config is:
```
env:
    PORT: 3001
with:
    port: ${{ secrets.SSH_PORT }}
```

So i had a error =>
**`2020/10/27 10:02:14 dial tcp ***:3001: i/o timeout`**

Looks like ssh uses `env.PORT` instead `with.port`
