### ISSUE TITLE
err: fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by t-lochhead** [appleboy/ssh-action#90]
Hi - I receive an error when I try to deploy a new update on my server.

I'm able to access the server, install npm, and restart pm2. But I can't pull an update from git for some reason. I get the following error:

`err: fatal: could not read Username for 'https://github.com': No such device or address`

How does one solve this error? It's a private repo btw.

**Comment by appleboy** [comment]
@t-lochhead I think this is not a problem with the ssh-action plugin. right?

**Comment by shmshd** [comment]
@t-lochhead No issue for me with private repo. Create a Personal Access Token and save the credentials in the server (`git config credential.helper store` and `git pull` manually once). Then re-run the workflow.

**Comment by fabri2000779** [comment]
i have the same issue, i have done this before and i can also do git pull and it wont request me credentials but when i run the github action pipeline gave to me same message

**Comment by t-lochhead** [comment]
@shmshd Thank you - this resolved my issue!

**Comment by kasir-barati** [comment]
> @t-lochhead No issue for me with private repo. Create a Personal Access Token and save the credentials in the server (`git config credential.helper store` and `git pull` manually once). Then re-run the workflow.

@shmshd this is not a good solution AFAIK. because you are doing some extra work to configure. Is there any better solution?

**Comment by EduardoJM** [comment]
> > @t-lochhead No issue for me with private repo. Create a Personal Access Token and save the credentials in the server (`git config credential.helper store` and `git pull` manually once). Then re-run the workflow.
> 
> @appleboy @shmshd this is not a good solution AFAIK. because you are doing some extra work to configure. Is there any better solution?

Here, in my small project, i used a full version of git pull with credentials (taken from https://stackoverflow.com/a/31835965):

```yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd tunelator-backend
            git pull https://EduardoJM:${{ secrets.AUTO_MERGE_TOKEN }}@github.com/tunelator/tunelator-backend/
            docker-compose down && docker-compose up --build -d
```

The EduardoJM is my github username, and the AUTO_MERGE_TOKEN secret is an access token (with repo scope) that is used for dependabot automerge and (for laziness purpose) i used then to made the git pull. tunelator is the organization name and tunelator-backend is the repository. That worked for my.
