### ISSUE TITLE
Issue on "sudo -i"

### ISSUE THREAD

**Issue by valspng** [appleboy/ssh-action#92]
Good day, 

Im currently experience on using command sudo -i.

err: mesg: ttyname failed: Inappropriate ioctl for device.

It works perfectly fine on my active sever but im getting an error. 

Thanks in advice.

**Comment by noudadrichem** [comment]
Same here... 
Searching for a way to run sudo commands as well.

**Comment by noudadrichem** [comment]
Fixed it with `sudo -S`

**Comment by anthonypillot** [comment]
Hello ! How I suppose to use `sudo` commands ?

`sudo -S` suppose to read password from standard input, but, I don't know how to do that ?

My config:

```yml 
 # Use SSH connection to remove remaining image, container and run a new container
  docker-run:
    name: Docker run container on server

    needs: docker-build-push

    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo "Delete remaining docker container"
            sudo -S docker container rm -f nginx-website
            [...]
```

Thanks for your help !
