### ISSUE TITLE
nohup command not working

### ISSUE THREAD

**Issue by junseol86** [appleboy/ssh-action#93]
I want to start my .jar file with ssh-action, but the action never completes because it runs on foreground even though I use nohup command.

```
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: nohup /directory/file.jar &
```

How should I write the script to start service in background?
